//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSBuildExtensionPack.WcfClientBLL
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBuildEventCodeServiceAsynChannel : MSBuildExtensionPack.WcfContracts.IBuildEventCodeServiceAsyn, System.ServiceModel.IClientChannel {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WcfClientEntityAsynBuildEventCode : System.ServiceModel.ClientBase<MSBuildExtensionPack.WcfContracts.IBuildEventCodeServiceAsyn>, MSBuildExtensionPack.WcfContracts.IBuildEventCodeServiceAsyn
    {

        #region Framework.DAL.DataAccessLayerContractBase<MSBuildExtensionPack.DataSourceEntities.BuildEventCodeCollection,MSBuildExtensionPack.DataSourceEntities.BuildEventCode,MSBuildExtensionPack.DataSourceEntities.BuildEventCodeIdentifier> Members

        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
        public partial class InsertEntityCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {

            private object[] results;

            public InsertEntityCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
                    base(exception, cancelled, userState) {
                this.results = results;
            }

            public MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeResponseMessageBuiltIn Result {
                get {
                    base.RaiseExceptionIfNecessary();
                    return ((MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeResponseMessageBuiltIn)(this.results[0]));
                }
            }
        }

        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
        public partial class UpdateEntityCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {

            private object[] results;

            public UpdateEntityCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
                    base(exception, cancelled, userState) {
                this.results = results;
            }

            public MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeResponseMessageBuiltIn Result {
                get {
                    base.RaiseExceptionIfNecessary();
                    return ((MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeResponseMessageBuiltIn)(this.results[0]));
                }
            }
        }

        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
        public partial class DeleteEntityCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {

            private object[] results;

            public DeleteEntityCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
                    base(exception, cancelled, userState) {
                this.results = results;
            }

            public MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeResponseMessageBuiltIn Result {
                get {
                    base.RaiseExceptionIfNecessary();
                    return ((MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeResponseMessageBuiltIn)(this.results[0]));
                }
            }
        }

        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
        public partial class DeleteByIdentifierEntityCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {

            private object[] results;

            public DeleteByIdentifierEntityCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
                    base(exception, cancelled, userState) {
                this.results = results;
            }

            public MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeResponseMessageBuiltIn Result {
                get {
                    base.RaiseExceptionIfNecessary();
                    return ((MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeResponseMessageBuiltIn)(this.results[0]));
                }
            }
        }

        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
        public partial class BatchInsertCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {

            private object[] results;

            public BatchInsertCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
                    base(exception, cancelled, userState) {
                this.results = results;
            }

            public MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeResponseMessageBuiltIn Result {
                get {
                    base.RaiseExceptionIfNecessary();
                    return ((MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeResponseMessageBuiltIn)(this.results[0]));
                }
            }
        }

        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
        public partial class BatchDeleteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {

            private object[] results;

            public BatchDeleteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
                    base(exception, cancelled, userState) {
                this.results = results;
            }

            public MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeResponseMessageBuiltIn Result {
                get {
                    base.RaiseExceptionIfNecessary();
                    return ((MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeResponseMessageBuiltIn)(this.results[0]));
                }
            }
        }

        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
        public partial class BatchUpdateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {

            private object[] results;

            public BatchUpdateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
                    base(exception, cancelled, userState) {
                this.results = results;
            }

            public MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeResponseMessageBuiltIn Result {
                get {
                    base.RaiseExceptionIfNecessary();
                    return ((MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeResponseMessageBuiltIn)(this.results[0]));
                }
            }
        }

        private BeginOperationDelegate onBeginInsertEntityDelegate;

        private EndOperationDelegate onEndInsertEntityDelegate;

        private System.Threading.SendOrPostCallback onInsertEntityCompletedDelegate;

        private BeginOperationDelegate onBeginUpdateEntityDelegate;

        private EndOperationDelegate onEndUpdateEntityDelegate;

        private System.Threading.SendOrPostCallback onUpdateEntityCompletedDelegate;

        private BeginOperationDelegate onBeginDeleteEntityDelegate;

        private EndOperationDelegate onEndDeleteEntityDelegate;

        private System.Threading.SendOrPostCallback onDeleteEntityCompletedDelegate;

        private BeginOperationDelegate onBeginDeleteByIdentifierEntityDelegate;

        private EndOperationDelegate onEndDeleteByIdentifierEntityDelegate;

        private System.Threading.SendOrPostCallback onDeleteByIdentifierEntityCompletedDelegate;

        private BeginOperationDelegate onBeginBatchInsertDelegate;

        private EndOperationDelegate onEndBatchInsertDelegate;

        private System.Threading.SendOrPostCallback onBatchInsertCompletedDelegate;

        private BeginOperationDelegate onBeginBatchDeleteDelegate;

        private EndOperationDelegate onEndBatchDeleteDelegate;

        private System.Threading.SendOrPostCallback onBatchDeleteCompletedDelegate;

        private BeginOperationDelegate onBeginBatchUpdateDelegate;

        private EndOperationDelegate onEndBatchUpdateDelegate;

        private System.Threading.SendOrPostCallback onBatchUpdateCompletedDelegate;

        #endregion Framework.DAL.DataAccessLayerContractBase<MSBuildExtensionPack.DataSourceEntities.BuildEventCodeCollection,MSBuildExtensionPack.DataSourceEntities.BuildEventCode,MSBuildExtensionPack.DataSourceEntities.BuildEventCodeIdentifier> Members

        #region Binary Columns

        #endregion Binary Columns

        // DataQueryPerQuerySettingCollection -- EventArg Classes And EventHandlers -- start

        #region Query Methods Of EntityOfCommon

        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
        public partial class GetCollectionOfEntityOfCommonCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
        {

            private object[] results;

            public GetCollectionOfEntityOfCommonCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
                base(exception, cancelled, userState)
            {
                this.results = results;
            }

            public MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeResponseMessageBuiltIn Result
            {
                get
                {
                    base.RaiseExceptionIfNecessary();
                    return ((MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeResponseMessageBuiltIn)(this.results[0]));
                }
            }
        }

        private BeginOperationDelegate onBeginGetCollectionOfEntityOfCommonDelegate;

        private EndOperationDelegate onEndGetCollectionOfEntityOfCommonDelegate;

        private System.Threading.SendOrPostCallback onGetCollectionOfEntityOfCommonCompletedDelegate;

        #endregion Query Methods Of EntityOfCommon

        #region Query Methods Of NameValuePairOfAll

        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
        public partial class GetCollectionOfNameValuePairOfAllCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
        {

            private object[] results;

            public GetCollectionOfNameValuePairOfAllCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
                base(exception, cancelled, userState)
            {
                this.results = results;
            }

            public Framework.CommonBLLEntities.BusinessLogicLayerResponseMessageNameValuePairCollection Result
            {
                get
                {
                    base.RaiseExceptionIfNecessary();
                    return ((Framework.CommonBLLEntities.BusinessLogicLayerResponseMessageNameValuePairCollection)(this.results[0]));
                }
            }
        }

        private BeginOperationDelegate onBeginGetCollectionOfNameValuePairOfAllDelegate;

        private EndOperationDelegate onEndGetCollectionOfNameValuePairOfAllDelegate;

        private System.Threading.SendOrPostCallback onGetCollectionOfNameValuePairOfAllCompletedDelegate;

        #endregion Query Methods Of NameValuePairOfAll

        #region Query Methods Of RssItemOfAll

        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
        public partial class GetCollectionOfRssItemOfAllCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
        {

            private object[] results;

            public GetCollectionOfRssItemOfAllCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
                base(exception, cancelled, userState)
            {
                this.results = results;
            }

            public Framework.CommonBLLEntities.BusinessLogicLayerResponseMessageRssItemCollection Result
            {
                get
                {
                    base.RaiseExceptionIfNecessary();
                    return ((Framework.CommonBLLEntities.BusinessLogicLayerResponseMessageRssItemCollection)(this.results[0]));
                }
            }
        }

        private BeginOperationDelegate onBeginGetCollectionOfRssItemOfAllDelegate;

        private EndOperationDelegate onEndGetCollectionOfRssItemOfAllDelegate;

        private System.Threading.SendOrPostCallback onGetCollectionOfRssItemOfAllCompletedDelegate;

        #endregion Query Methods Of RssItemOfAll

        #region Query Methods Of EntityOfByIdentifier

        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
        public partial class GetCollectionOfEntityOfByIdentifierCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
        {

            private object[] results;

            public GetCollectionOfEntityOfByIdentifierCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
                base(exception, cancelled, userState)
            {
                this.results = results;
            }

            public MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeResponseMessageBuiltIn Result
            {
                get
                {
                    base.RaiseExceptionIfNecessary();
                    return ((MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeResponseMessageBuiltIn)(this.results[0]));
                }
            }
        }

        private BeginOperationDelegate onBeginGetCollectionOfEntityOfByIdentifierDelegate;

        private EndOperationDelegate onEndGetCollectionOfEntityOfByIdentifierDelegate;

        private System.Threading.SendOrPostCallback onGetCollectionOfEntityOfByIdentifierCompletedDelegate;

        #endregion Query Methods Of EntityOfByIdentifier

        #region Query Methods Of KeyInformationOfByIdentifier

        [System.Diagnostics.DebuggerStepThroughAttribute()]
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
        public partial class GetCollectionOfKeyInformationOfByIdentifierCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
        {

            private object[] results;

            public GetCollectionOfKeyInformationOfByIdentifierCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
                base(exception, cancelled, userState)
            {
                this.results = results;
            }

            public MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeResponseMessageBuiltIn.KeyInformation Result
            {
                get
                {
                    base.RaiseExceptionIfNecessary();
                    return ((MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeResponseMessageBuiltIn.KeyInformation)(this.results[0]));
                }
            }
        }

        private BeginOperationDelegate onBeginGetCollectionOfKeyInformationOfByIdentifierDelegate;

        private EndOperationDelegate onEndGetCollectionOfKeyInformationOfByIdentifierDelegate;

        private System.Threading.SendOrPostCallback onGetCollectionOfKeyInformationOfByIdentifierCompletedDelegate;

        #endregion Query Methods Of KeyInformationOfByIdentifier

        // DataQueryPerQuerySettingCollection -- EventArg Classes And EventHandlers -- end

        #region GetAscendantAndDescendant

        #endregion GetAscendantAndDescendant

        #region Open and Close

        private BeginOperationDelegate onBeginOpenDelegate;

        private EndOperationDelegate onEndOpenDelegate;

        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;

        private BeginOperationDelegate onBeginCloseDelegate;

        private EndOperationDelegate onEndCloseDelegate;

        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;

        #endregion Open and Close

        #region constructors

        public WcfClientEntityAsynBuildEventCode()
        {
        }

        public WcfClientEntityAsynBuildEventCode(string endpointConfigurationName) :
            base(endpointConfigurationName)
        {
        }

        public WcfClientEntityAsynBuildEventCode(string endpointConfigurationName, string remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
        {
        }

        public WcfClientEntityAsynBuildEventCode(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
            base(endpointConfigurationName, remoteAddress)
        {
        }

        public WcfClientEntityAsynBuildEventCode(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
            base(binding, remoteAddress)
        {
        }

        #endregion constructors

#if WINDOWS_PHONE
        public System.Net.CookieContainer CookieContainer
        {
            get
            {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null))
                {
                    return httpCookieContainerManager.CookieContainer;
                }
                else
                {
                    return null;
                }
            }
            set
            {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null))
                {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else
                {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }

#endif

        #region Framework.DAL.DataAccessLayerContractBase<MSBuildExtensionPack.DataSourceEntities.BuildEventCodeCollection,MSBuildExtensionPack.DataSourceEntities.BuildEventCode,MSBuildExtensionPack.DataSourceEntities.BuildEventCodeIdentifier> Members

        public event System.EventHandler<InsertEntityCompletedEventArgs> InsertEntityCompleted;

        public event System.EventHandler<UpdateEntityCompletedEventArgs> UpdateEntityCompleted;

        public event System.EventHandler<DeleteEntityCompletedEventArgs> DeleteEntityCompleted;

        public event System.EventHandler<DeleteByIdentifierEntityCompletedEventArgs> DeleteByIdentifierEntityCompleted;

        public event System.EventHandler<BatchInsertCompletedEventArgs> BatchInsertCompleted;

        public event System.EventHandler<BatchDeleteCompletedEventArgs> BatchDeleteCompleted;

        public event System.EventHandler<BatchUpdateCompletedEventArgs> BatchUpdateCompleted;

        #endregion Framework.DAL.DataAccessLayerContractBase<MSBuildExtensionPack.DataSourceEntities.BuildEventCodeCollection,MSBuildExtensionPack.DataSourceEntities.BuildEventCode,MSBuildExtensionPack.DataSourceEntities.BuildEventCodeIdentifier> Members

        #region Binary Columns

        #endregion Binary Columns

        // DataQueryPerQuerySettingCollection -- EventHandlers -- Start

        #region Query Methods Of EntityOfCommon

        public event System.EventHandler<GetCollectionOfEntityOfCommonCompletedEventArgs> GetCollectionOfEntityOfCommonCompleted;

        #endregion Query Methods Of EntityOfCommon

        #region Query Methods Of NameValuePairOfAll

        public event System.EventHandler<GetCollectionOfNameValuePairOfAllCompletedEventArgs> GetCollectionOfNameValuePairOfAllCompleted;

        #endregion Query Methods Of NameValuePairOfAll

        #region Query Methods Of RssItemOfAll

        public event System.EventHandler<GetCollectionOfRssItemOfAllCompletedEventArgs> GetCollectionOfRssItemOfAllCompleted;

        #endregion Query Methods Of RssItemOfAll

        #region Query Methods Of EntityOfByIdentifier

        public event System.EventHandler<GetCollectionOfEntityOfByIdentifierCompletedEventArgs> GetCollectionOfEntityOfByIdentifierCompleted;

        #endregion Query Methods Of EntityOfByIdentifier

        #region Query Methods Of KeyInformationOfByIdentifier

        public event System.EventHandler<GetCollectionOfKeyInformationOfByIdentifierCompletedEventArgs> GetCollectionOfKeyInformationOfByIdentifierCompleted;

        #endregion Query Methods Of KeyInformationOfByIdentifier

        // DataQueryPerQuerySettingCollection -- EventHandlers -- End

        #region GetAscendantAndDescendant

        #endregion GetAscendantAndDescendant

        #region Open and Close

        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;

        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;

        #endregion Open and Close

        #region Framework.DAL.DataAccessLayerContractBase<MSBuildExtensionPack.DataSourceEntities.BuildEventCodeCollection,MSBuildExtensionPack.DataSourceEntities.BuildEventCode,MSBuildExtensionPack.DataSourceEntities.BuildEventCodeIdentifier> Members

        /// <summary>
        /// Inserts the specified input.
        /// </summary>
        /// <param name="request">The request.</param>
        /// <returns>a message with action result</returns>
        public MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeResponseMessageBuiltIn InsertEntity(MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeRequestMessageBuiltIn request)
        {
            return base.Channel.InsertEntity(request);
        }

        /// <summary>
        /// Updates the specified input.
        /// </summary>
        /// <param name="request">The request.</param>
        /// <returns>a message with action result</returns>
        public MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeResponseMessageBuiltIn UpdateEntity(MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeRequestMessageBuiltIn request)
        {
            return base.Channel.UpdateEntity(request);
        }

        /// <summary>
        /// Deletes the specified input.
        /// </summary>
        /// <param name="request">The request.</param>
        /// <returns>a message with action result</returns>
        public MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeResponseMessageBuiltIn DeleteEntity(MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeRequestMessageBuiltIn request)
        {
            return base.Channel.DeleteEntity(request);
        }

        /// <summary>
        /// Deletes the by identifier.
        /// </summary>
        /// <param name="id">The id.</param>
        /// <returns>a message with action result</returns>
        public MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeResponseMessageBuiltIn DeleteByIdentifierEntity(MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeRequestMessageBuiltInOfIdentifier id)
        {
            return base.Channel.DeleteByIdentifierEntity(id);
        }

        /// <summary>
        /// Batches the insert.
        /// </summary>
        /// <param name="request">The request.</param>
        /// <returns>a message with action result</returns>
        public MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeResponseMessageBuiltIn BatchInsert(MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeRequestMessageBuiltIn request)
        {
            return base.Channel.BatchInsert(request);
        }

        /// <summary>
        /// Batches the delete.
        /// </summary>
        /// <param name="request">The request.</param>
        /// <returns>a message with action result</returns>
        public MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeResponseMessageBuiltIn BatchDelete(MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeRequestMessageBuiltIn request)
        {
            return base.Channel.InsertEntity(request);
        }

        /// <summary>
        /// Batches the update.
        /// </summary>
        /// <param name="request">The request.</param>
        /// <returns>a message with action result</returns>
        public MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeResponseMessageBuiltIn BatchUpdate(MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeRequestMessageBuiltIn request)
        {
            return base.Channel.BatchUpdate(request);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult MSBuildExtensionPack.WcfContracts.IBuildEventCodeServiceAsyn.BeginInsertEntity(MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeRequestMessageBuiltIn input, System.AsyncCallback callback, object asyncState)
        {
            return base.Channel.BeginInsertEntity(input, callback, asyncState);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeResponseMessageBuiltIn MSBuildExtensionPack.WcfContracts.IBuildEventCodeServiceAsyn.EndInsertEntity(System.IAsyncResult result)
        {
            return base.Channel.EndInsertEntity(result);
        }

        private System.IAsyncResult OnBeginInsertEntity(object[] inValues, System.AsyncCallback callback, object asyncState)
        {
            MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeRequestMessageBuiltIn input = ((MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeRequestMessageBuiltIn)(inValues[0]));
            return ((MSBuildExtensionPack.WcfContracts.IBuildEventCodeServiceAsyn)(this)).BeginInsertEntity(input, callback, asyncState);
        }

        private object[] OnEndInsertEntity(System.IAsyncResult result)
        {
            MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeResponseMessageBuiltIn retVal = ((MSBuildExtensionPack.WcfContracts.IBuildEventCodeServiceAsyn)(this)).EndInsertEntity(result);
            return new object[] {
                    retVal};
        }

        private void OnInsertEntityCompleted(object state)
        {
            if ((this.InsertEntityCompleted != null))
            {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.InsertEntityCompleted(this, new InsertEntityCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }

        public void InsertEntityAsync(MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeRequestMessageBuiltIn input)
        {
            this.InsertEntityAsync(input, null);
        }

        public void InsertEntityAsync(MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeRequestMessageBuiltIn input, object userState)
        {
            if ((this.onBeginInsertEntityDelegate == null))
            {
                this.onBeginInsertEntityDelegate = new BeginOperationDelegate(this.OnBeginInsertEntity);
            }
            if ((this.onEndInsertEntityDelegate == null))
            {
                this.onEndInsertEntityDelegate = new EndOperationDelegate(this.OnEndInsertEntity);
            }
            if ((this.onInsertEntityCompletedDelegate == null))
            {
                this.onInsertEntityCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnInsertEntityCompleted);
            }
            base.InvokeAsync(this.onBeginInsertEntityDelegate, new object[] {
                        input}, this.onEndInsertEntityDelegate, this.onInsertEntityCompletedDelegate, userState);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult MSBuildExtensionPack.WcfContracts.IBuildEventCodeServiceAsyn.BeginUpdateEntity(MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeRequestMessageBuiltIn input, System.AsyncCallback callback, object asyncState)
        {
            return base.Channel.BeginUpdateEntity(input, callback, asyncState);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeResponseMessageBuiltIn MSBuildExtensionPack.WcfContracts.IBuildEventCodeServiceAsyn.EndUpdateEntity(System.IAsyncResult result)
        {
            return base.Channel.EndUpdateEntity(result);
        }

        private System.IAsyncResult OnBeginUpdateEntity(object[] inValues, System.AsyncCallback callback, object asyncState)
        {
            MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeRequestMessageBuiltIn input = ((MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeRequestMessageBuiltIn)(inValues[0]));
            return ((MSBuildExtensionPack.WcfContracts.IBuildEventCodeServiceAsyn)(this)).BeginUpdateEntity(input, callback, asyncState);
        }

        private object[] OnEndUpdateEntity(System.IAsyncResult result)
        {
            MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeResponseMessageBuiltIn retVal = ((MSBuildExtensionPack.WcfContracts.IBuildEventCodeServiceAsyn)(this)).EndUpdateEntity(result);
            return new object[] {
                    retVal};
        }

        private void OnUpdateEntityCompleted(object state)
        {
            if ((this.UpdateEntityCompleted != null))
            {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.UpdateEntityCompleted(this, new UpdateEntityCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }

        public void UpdateEntityAsync(MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeRequestMessageBuiltIn input)
        {
            this.UpdateEntityAsync(input, null);
        }

        public void UpdateEntityAsync(MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeRequestMessageBuiltIn input, object userState)
        {
            if ((this.onBeginUpdateEntityDelegate == null))
            {
                this.onBeginUpdateEntityDelegate = new BeginOperationDelegate(this.OnBeginUpdateEntity);
            }
            if ((this.onEndUpdateEntityDelegate == null))
            {
                this.onEndUpdateEntityDelegate = new EndOperationDelegate(this.OnEndUpdateEntity);
            }
            if ((this.onUpdateEntityCompletedDelegate == null))
            {
                this.onUpdateEntityCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnUpdateEntityCompleted);
            }
            base.InvokeAsync(this.onBeginUpdateEntityDelegate, new object[] {
                        input}, this.onEndUpdateEntityDelegate, this.onUpdateEntityCompletedDelegate, userState);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult MSBuildExtensionPack.WcfContracts.IBuildEventCodeServiceAsyn.BeginDeleteEntity(MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeRequestMessageBuiltIn input, System.AsyncCallback callback, object asyncState)
        {
            return base.Channel.BeginDeleteEntity(input, callback, asyncState);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeResponseMessageBuiltIn MSBuildExtensionPack.WcfContracts.IBuildEventCodeServiceAsyn.EndDeleteEntity(System.IAsyncResult result)
        {
            return base.Channel.EndDeleteEntity(result);
        }

        private System.IAsyncResult OnBeginDeleteEntity(object[] inValues, System.AsyncCallback callback, object asyncState)
        {
            MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeRequestMessageBuiltIn input = ((MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeRequestMessageBuiltIn)(inValues[0]));
            return ((MSBuildExtensionPack.WcfContracts.IBuildEventCodeServiceAsyn)(this)).BeginDeleteEntity(input, callback, asyncState);
        }

        private object[] OnEndDeleteEntity(System.IAsyncResult result)
        {
            MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeResponseMessageBuiltIn retVal = ((MSBuildExtensionPack.WcfContracts.IBuildEventCodeServiceAsyn)(this)).EndDeleteEntity(result);
            return new object[] {
                    retVal};
        }

        private void OnDeleteEntityCompleted(object state)
        {
            if ((this.DeleteEntityCompleted != null))
            {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.DeleteEntityCompleted(this, new DeleteEntityCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }

        public void DeleteEntityAsync(MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeRequestMessageBuiltIn input)
        {
            this.DeleteEntityAsync(input, null);
        }

        public void DeleteEntityAsync(MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeRequestMessageBuiltIn input, object userState)
        {
            if ((this.onBeginDeleteEntityDelegate == null))
            {
                this.onBeginDeleteEntityDelegate = new BeginOperationDelegate(this.OnBeginDeleteEntity);
            }
            if ((this.onEndDeleteEntityDelegate == null))
            {
                this.onEndDeleteEntityDelegate = new EndOperationDelegate(this.OnEndDeleteEntity);
            }
            if ((this.onDeleteEntityCompletedDelegate == null))
            {
                this.onDeleteEntityCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnDeleteEntityCompleted);
            }
            base.InvokeAsync(this.onBeginDeleteEntityDelegate, new object[] {
                        input}, this.onEndDeleteEntityDelegate, this.onDeleteEntityCompletedDelegate, userState);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult MSBuildExtensionPack.WcfContracts.IBuildEventCodeServiceAsyn.BeginDeleteByIdentifierEntity(MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeRequestMessageBuiltInOfIdentifier id, System.AsyncCallback callback, object asyncState)
        {
            return base.Channel.BeginDeleteByIdentifierEntity(id, callback, asyncState);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeResponseMessageBuiltIn MSBuildExtensionPack.WcfContracts.IBuildEventCodeServiceAsyn.EndDeleteByIdentifierEntity(System.IAsyncResult result)
        {
            return base.Channel.EndDeleteByIdentifierEntity(result);
        }

        private System.IAsyncResult OnBeginDeleteByIdentifierEntity(object[] inValues, System.AsyncCallback callback, object asyncState)
        {
            MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeRequestMessageBuiltInOfIdentifier id = ((MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeRequestMessageBuiltInOfIdentifier)(inValues[0]));
            return ((MSBuildExtensionPack.WcfContracts.IBuildEventCodeServiceAsyn)(this)).BeginDeleteByIdentifierEntity(id, callback, asyncState);
        }

        private object[] OnEndDeleteByIdentifierEntity(System.IAsyncResult result)
        {
            MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeResponseMessageBuiltIn retVal = ((MSBuildExtensionPack.WcfContracts.IBuildEventCodeServiceAsyn)(this)).EndDeleteByIdentifierEntity(result);
            return new object[] {
                    retVal};
        }

        private void OnDeleteByIdentifierEntityCompleted(object state)
        {
            if ((this.DeleteByIdentifierEntityCompleted != null))
            {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.DeleteByIdentifierEntityCompleted(this, new DeleteByIdentifierEntityCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }

        public void DeleteByIdentifierEntityAsync(MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeRequestMessageBuiltInOfIdentifier id)
        {
            this.DeleteByIdentifierEntityAsync(id, null);
        }

        public void DeleteByIdentifierEntityAsync(MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeRequestMessageBuiltInOfIdentifier id, object userState)
        {
            if ((this.onBeginDeleteByIdentifierEntityDelegate == null))
            {
                this.onBeginDeleteByIdentifierEntityDelegate = new BeginOperationDelegate(this.OnBeginDeleteByIdentifierEntity);
            }
            if ((this.onEndDeleteByIdentifierEntityDelegate == null))
            {
                this.onEndDeleteByIdentifierEntityDelegate = new EndOperationDelegate(this.OnEndDeleteByIdentifierEntity);
            }
            if ((this.onDeleteByIdentifierEntityCompletedDelegate == null))
            {
                this.onDeleteByIdentifierEntityCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnDeleteByIdentifierEntityCompleted);
            }
            base.InvokeAsync(this.onBeginDeleteByIdentifierEntityDelegate, new object[] {
                        id}, this.onEndDeleteByIdentifierEntityDelegate, this.onDeleteByIdentifierEntityCompletedDelegate, userState);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult MSBuildExtensionPack.WcfContracts.IBuildEventCodeServiceAsyn.BeginBatchInsert(MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeRequestMessageBuiltIn input, System.AsyncCallback callback, object asyncState)
        {
            return base.Channel.BeginBatchInsert(input, callback, asyncState);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeResponseMessageBuiltIn MSBuildExtensionPack.WcfContracts.IBuildEventCodeServiceAsyn.EndBatchInsert(System.IAsyncResult result)
        {
            return base.Channel.EndBatchInsert(result);
        }

        private System.IAsyncResult OnBeginBatchInsert(object[] inValues, System.AsyncCallback callback, object asyncState)
        {
            MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeRequestMessageBuiltIn input = ((MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeRequestMessageBuiltIn)(inValues[0]));
            return ((MSBuildExtensionPack.WcfContracts.IBuildEventCodeServiceAsyn)(this)).BeginBatchInsert(input, callback, asyncState);
        }

        private object[] OnEndBatchInsert(System.IAsyncResult result)
        {
            MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeResponseMessageBuiltIn retVal = ((MSBuildExtensionPack.WcfContracts.IBuildEventCodeServiceAsyn)(this)).EndBatchInsert(result);
            return new object[] {
                    retVal};
        }

        private void OnBatchInsertCompleted(object state)
        {
            if ((this.BatchInsertCompleted != null))
            {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.BatchInsertCompleted(this, new BatchInsertCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }

        public void BatchInsertAsync(MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeRequestMessageBuiltIn input)
        {
            this.BatchInsertAsync(input, null);
        }

        public void BatchInsertAsync(MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeRequestMessageBuiltIn input, object userState)
        {
            if ((this.onBeginBatchInsertDelegate == null))
            {
                this.onBeginBatchInsertDelegate = new BeginOperationDelegate(this.OnBeginBatchInsert);
            }
            if ((this.onEndBatchInsertDelegate == null))
            {
                this.onEndBatchInsertDelegate = new EndOperationDelegate(this.OnEndBatchInsert);
            }
            if ((this.onBatchInsertCompletedDelegate == null))
            {
                this.onBatchInsertCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnBatchInsertCompleted);
            }
            base.InvokeAsync(this.onBeginBatchInsertDelegate, new object[] {
                        input}, this.onEndBatchInsertDelegate, this.onBatchInsertCompletedDelegate, userState);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult MSBuildExtensionPack.WcfContracts.IBuildEventCodeServiceAsyn.BeginBatchDelete(MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeRequestMessageBuiltIn input, System.AsyncCallback callback, object asyncState)
        {
            return base.Channel.BeginBatchDelete(input, callback, asyncState);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeResponseMessageBuiltIn MSBuildExtensionPack.WcfContracts.IBuildEventCodeServiceAsyn.EndBatchDelete(System.IAsyncResult result)
        {
            return base.Channel.EndBatchDelete(result);
        }

        private System.IAsyncResult OnBeginBatchDelete(object[] inValues, System.AsyncCallback callback, object asyncState)
        {
            MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeRequestMessageBuiltIn input = ((MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeRequestMessageBuiltIn)(inValues[0]));
            return ((MSBuildExtensionPack.WcfContracts.IBuildEventCodeServiceAsyn)(this)).BeginBatchDelete(input, callback, asyncState);
        }

        private object[] OnEndBatchDelete(System.IAsyncResult result)
        {
            MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeResponseMessageBuiltIn retVal = ((MSBuildExtensionPack.WcfContracts.IBuildEventCodeServiceAsyn)(this)).EndBatchDelete(result);
            return new object[] {
                    retVal};
        }

        private void OnBatchDeleteCompleted(object state)
        {
            if ((this.BatchDeleteCompleted != null))
            {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.BatchDeleteCompleted(this, new BatchDeleteCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }

        public void BatchDeleteAsync(MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeRequestMessageBuiltIn input)
        {
            this.BatchDeleteAsync(input, null);
        }

        public void BatchDeleteAsync(MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeRequestMessageBuiltIn input, object userState)
        {
            if ((this.onBeginBatchDeleteDelegate == null))
            {
                this.onBeginBatchDeleteDelegate = new BeginOperationDelegate(this.OnBeginBatchDelete);
            }
            if ((this.onEndBatchDeleteDelegate == null))
            {
                this.onEndBatchDeleteDelegate = new EndOperationDelegate(this.OnEndBatchDelete);
            }
            if ((this.onBatchDeleteCompletedDelegate == null))
            {
                this.onBatchDeleteCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnBatchDeleteCompleted);
            }
            base.InvokeAsync(this.onBeginBatchDeleteDelegate, new object[] {
                        input}, this.onEndBatchDeleteDelegate, this.onBatchDeleteCompletedDelegate, userState);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult MSBuildExtensionPack.WcfContracts.IBuildEventCodeServiceAsyn.BeginBatchUpdate(MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeRequestMessageBuiltIn input, System.AsyncCallback callback, object asyncState)
        {
            return base.Channel.BeginBatchUpdate(input, callback, asyncState);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeResponseMessageBuiltIn MSBuildExtensionPack.WcfContracts.IBuildEventCodeServiceAsyn.EndBatchUpdate(System.IAsyncResult result)
        {
            return base.Channel.EndBatchUpdate(result);
        }

        private System.IAsyncResult OnBeginBatchUpdate(object[] inValues, System.AsyncCallback callback, object asyncState)
        {
            MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeRequestMessageBuiltIn input = ((MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeRequestMessageBuiltIn)(inValues[0]));
            return ((MSBuildExtensionPack.WcfContracts.IBuildEventCodeServiceAsyn)(this)).BeginBatchUpdate(input, callback, asyncState);
        }

        private object[] OnEndBatchUpdate(System.IAsyncResult result)
        {
            MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeResponseMessageBuiltIn retVal = ((MSBuildExtensionPack.WcfContracts.IBuildEventCodeServiceAsyn)(this)).EndBatchUpdate(result);
            return new object[] {
                    retVal};
        }

        private void OnBatchUpdateCompleted(object state)
        {
            if ((this.BatchUpdateCompleted != null))
            {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.BatchUpdateCompleted(this, new BatchUpdateCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }

        public void BatchUpdateAsync(MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeRequestMessageBuiltIn input)
        {
            this.BatchUpdateAsync(input, null);
        }

        public void BatchUpdateAsync(MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeRequestMessageBuiltIn input, object userState)
        {
            if ((this.onBeginBatchUpdateDelegate == null))
            {
                this.onBeginBatchUpdateDelegate = new BeginOperationDelegate(this.OnBeginBatchUpdate);
            }
            if ((this.onEndBatchUpdateDelegate == null))
            {
                this.onEndBatchUpdateDelegate = new EndOperationDelegate(this.OnEndBatchUpdate);
            }
            if ((this.onBatchUpdateCompletedDelegate == null))
            {
                this.onBatchUpdateCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnBatchUpdateCompleted);
            }
            base.InvokeAsync(this.onBeginBatchUpdateDelegate, new object[] {
                        input}, this.onEndBatchUpdateDelegate, this.onBatchUpdateCompletedDelegate, userState);
        }

        #endregion Framework.DAL.DataAccessLayerContractBase<MSBuildExtensionPack.DataSourceEntities.BuildEventCodeCollection,MSBuildExtensionPack.DataSourceEntities.BuildEventCode,MSBuildExtensionPack.DataSourceEntities.BuildEventCodeIdentifier> Members

        #region Binary Columns

        #endregion Binary Columns

        // DataQueryPerQuerySettingCollection -- InClient -- Start

        #region Query Methods Of EntityOfCommon

        /// <summary>
        /// Gets the collection of entity of "Common".
        /// </summary>
        /// <param name="request">The request.</param>
        /// <returns></returns>
        public MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeResponseMessageBuiltIn GetCollectionOfEntityOfCommon(
            MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeRequestMessageUserDefinedOfCommon request)
        {
            return base.Channel.GetCollectionOfEntityOfCommon(request);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult MSBuildExtensionPack.WcfContracts.IBuildEventCodeServiceAsyn.BeginGetCollectionOfEntityOfCommon(MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeRequestMessageUserDefinedOfCommon request, System.AsyncCallback callback, object asyncState)
        {
            return base.Channel.BeginGetCollectionOfEntityOfCommon(request, callback, asyncState);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeResponseMessageBuiltIn MSBuildExtensionPack.WcfContracts.IBuildEventCodeServiceAsyn.EndGetCollectionOfEntityOfCommon(System.IAsyncResult result)
        {
            return base.Channel.EndGetCollectionOfEntityOfCommon(result);
        }

        private System.IAsyncResult OnBeginGetCollectionOfEntityOfCommon(object[] inValues, System.AsyncCallback callback, object asyncState)
        {
            MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeRequestMessageUserDefinedOfCommon request = ((MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeRequestMessageUserDefinedOfCommon )(inValues[0]));
            return ((MSBuildExtensionPack.WcfContracts.IBuildEventCodeServiceAsyn)(this)).BeginGetCollectionOfEntityOfCommon(request, callback, asyncState);
        }

        private object[] OnEndGetCollectionOfEntityOfCommon(System.IAsyncResult result)
        {
            MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeResponseMessageBuiltIn retVal = ((MSBuildExtensionPack.WcfContracts.IBuildEventCodeServiceAsyn)(this)).EndGetCollectionOfEntityOfCommon(result);
            return new object[] {
                    retVal};
        }

        private void OnGetCollectionOfEntityOfCommonCompleted(object state)
        {
            if ((this.GetCollectionOfEntityOfCommonCompleted != null))
            {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetCollectionOfEntityOfCommonCompleted(this, new GetCollectionOfEntityOfCommonCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }

        public void GetCollectionOfEntityOfCommonAsync(MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeRequestMessageUserDefinedOfCommon request)
        {
            this.GetCollectionOfEntityOfCommonAsync(request, null);
        }

        public void GetCollectionOfEntityOfCommonAsync(MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeRequestMessageUserDefinedOfCommon request, object userState)
        {
            if ((this.onBeginGetCollectionOfEntityOfCommonDelegate == null))
            {
                this.onBeginGetCollectionOfEntityOfCommonDelegate = new BeginOperationDelegate(this.OnBeginGetCollectionOfEntityOfCommon);
            }
            if ((this.onEndGetCollectionOfEntityOfCommonDelegate == null))
            {
                this.onEndGetCollectionOfEntityOfCommonDelegate = new EndOperationDelegate(this.OnEndGetCollectionOfEntityOfCommon);
            }
            if ((this.onGetCollectionOfEntityOfCommonCompletedDelegate == null))
            {
                this.onGetCollectionOfEntityOfCommonCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetCollectionOfEntityOfCommonCompleted);
            }
            base.InvokeAsync(this.onBeginGetCollectionOfEntityOfCommonDelegate, new object[] {
                        request}, this.onEndGetCollectionOfEntityOfCommonDelegate, this.onGetCollectionOfEntityOfCommonCompletedDelegate, userState);
        }

        #endregion Query Methods Of EntityOfCommon

        #region Query Methods Of NameValuePairOfAll

        /// <summary>
        /// Gets the collection of entity of "All".
        /// </summary>
        /// <param name="request">The request.</param>
        /// <returns></returns>
        public Framework.CommonBLLEntities.BusinessLogicLayerResponseMessageNameValuePairCollection GetCollectionOfNameValuePairOfAll(
            MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeRequestMessageUserDefinedOfAll request)
        {
            return base.Channel.GetCollectionOfNameValuePairOfAll(request);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult MSBuildExtensionPack.WcfContracts.IBuildEventCodeServiceAsyn.BeginGetCollectionOfNameValuePairOfAll(MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeRequestMessageUserDefinedOfAll request, System.AsyncCallback callback, object asyncState)
        {
            return base.Channel.BeginGetCollectionOfNameValuePairOfAll(request, callback, asyncState);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Framework.CommonBLLEntities.BusinessLogicLayerResponseMessageNameValuePairCollection MSBuildExtensionPack.WcfContracts.IBuildEventCodeServiceAsyn.EndGetCollectionOfNameValuePairOfAll(System.IAsyncResult result)
        {
            return base.Channel.EndGetCollectionOfNameValuePairOfAll(result);
        }

        private System.IAsyncResult OnBeginGetCollectionOfNameValuePairOfAll(object[] inValues, System.AsyncCallback callback, object asyncState)
        {
            MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeRequestMessageUserDefinedOfAll request = ((MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeRequestMessageUserDefinedOfAll )(inValues[0]));
            return ((MSBuildExtensionPack.WcfContracts.IBuildEventCodeServiceAsyn)(this)).BeginGetCollectionOfNameValuePairOfAll(request, callback, asyncState);
        }

        private object[] OnEndGetCollectionOfNameValuePairOfAll(System.IAsyncResult result)
        {
            Framework.CommonBLLEntities.BusinessLogicLayerResponseMessageNameValuePairCollection retVal = ((MSBuildExtensionPack.WcfContracts.IBuildEventCodeServiceAsyn)(this)).EndGetCollectionOfNameValuePairOfAll(result);
            return new object[] {
                    retVal};
        }

        private void OnGetCollectionOfNameValuePairOfAllCompleted(object state)
        {
            if ((this.GetCollectionOfNameValuePairOfAllCompleted != null))
            {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetCollectionOfNameValuePairOfAllCompleted(this, new GetCollectionOfNameValuePairOfAllCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }

        public void GetCollectionOfNameValuePairOfAllAsync(MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeRequestMessageUserDefinedOfAll request)
        {
            this.GetCollectionOfNameValuePairOfAllAsync(request, null);
        }

        public void GetCollectionOfNameValuePairOfAllAsync(MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeRequestMessageUserDefinedOfAll request, object userState)
        {
            if ((this.onBeginGetCollectionOfNameValuePairOfAllDelegate == null))
            {
                this.onBeginGetCollectionOfNameValuePairOfAllDelegate = new BeginOperationDelegate(this.OnBeginGetCollectionOfNameValuePairOfAll);
            }
            if ((this.onEndGetCollectionOfNameValuePairOfAllDelegate == null))
            {
                this.onEndGetCollectionOfNameValuePairOfAllDelegate = new EndOperationDelegate(this.OnEndGetCollectionOfNameValuePairOfAll);
            }
            if ((this.onGetCollectionOfNameValuePairOfAllCompletedDelegate == null))
            {
                this.onGetCollectionOfNameValuePairOfAllCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetCollectionOfNameValuePairOfAllCompleted);
            }
            base.InvokeAsync(this.onBeginGetCollectionOfNameValuePairOfAllDelegate, new object[] {
                        request}, this.onEndGetCollectionOfNameValuePairOfAllDelegate, this.onGetCollectionOfNameValuePairOfAllCompletedDelegate, userState);
        }

        #endregion Query Methods Of NameValuePairOfAll

        #region Query Methods Of RssItemOfAll

        /// <summary>
        /// Gets the collection of entity of "All".
        /// </summary>
        /// <param name="request">The request.</param>
        /// <returns></returns>
        public Framework.CommonBLLEntities.BusinessLogicLayerResponseMessageRssItemCollection GetCollectionOfRssItemOfAll(
            MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeRequestMessageUserDefinedOfAll request)
        {
            return base.Channel.GetCollectionOfRssItemOfAll(request);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult MSBuildExtensionPack.WcfContracts.IBuildEventCodeServiceAsyn.BeginGetCollectionOfRssItemOfAll(MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeRequestMessageUserDefinedOfAll request, System.AsyncCallback callback, object asyncState)
        {
            return base.Channel.BeginGetCollectionOfRssItemOfAll(request, callback, asyncState);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Framework.CommonBLLEntities.BusinessLogicLayerResponseMessageRssItemCollection MSBuildExtensionPack.WcfContracts.IBuildEventCodeServiceAsyn.EndGetCollectionOfRssItemOfAll(System.IAsyncResult result)
        {
            return base.Channel.EndGetCollectionOfRssItemOfAll(result);
        }

        private System.IAsyncResult OnBeginGetCollectionOfRssItemOfAll(object[] inValues, System.AsyncCallback callback, object asyncState)
        {
            MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeRequestMessageUserDefinedOfAll request = ((MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeRequestMessageUserDefinedOfAll )(inValues[0]));
            return ((MSBuildExtensionPack.WcfContracts.IBuildEventCodeServiceAsyn)(this)).BeginGetCollectionOfRssItemOfAll(request, callback, asyncState);
        }

        private object[] OnEndGetCollectionOfRssItemOfAll(System.IAsyncResult result)
        {
            Framework.CommonBLLEntities.BusinessLogicLayerResponseMessageRssItemCollection retVal = ((MSBuildExtensionPack.WcfContracts.IBuildEventCodeServiceAsyn)(this)).EndGetCollectionOfRssItemOfAll(result);
            return new object[] {
                    retVal};
        }

        private void OnGetCollectionOfRssItemOfAllCompleted(object state)
        {
            if ((this.GetCollectionOfRssItemOfAllCompleted != null))
            {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetCollectionOfRssItemOfAllCompleted(this, new GetCollectionOfRssItemOfAllCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }

        public void GetCollectionOfRssItemOfAllAsync(MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeRequestMessageUserDefinedOfAll request)
        {
            this.GetCollectionOfRssItemOfAllAsync(request, null);
        }

        public void GetCollectionOfRssItemOfAllAsync(MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeRequestMessageUserDefinedOfAll request, object userState)
        {
            if ((this.onBeginGetCollectionOfRssItemOfAllDelegate == null))
            {
                this.onBeginGetCollectionOfRssItemOfAllDelegate = new BeginOperationDelegate(this.OnBeginGetCollectionOfRssItemOfAll);
            }
            if ((this.onEndGetCollectionOfRssItemOfAllDelegate == null))
            {
                this.onEndGetCollectionOfRssItemOfAllDelegate = new EndOperationDelegate(this.OnEndGetCollectionOfRssItemOfAll);
            }
            if ((this.onGetCollectionOfRssItemOfAllCompletedDelegate == null))
            {
                this.onGetCollectionOfRssItemOfAllCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetCollectionOfRssItemOfAllCompleted);
            }
            base.InvokeAsync(this.onBeginGetCollectionOfRssItemOfAllDelegate, new object[] {
                        request}, this.onEndGetCollectionOfRssItemOfAllDelegate, this.onGetCollectionOfRssItemOfAllCompletedDelegate, userState);
        }

        #endregion Query Methods Of RssItemOfAll

        #region Query Methods Of EntityOfByIdentifier

        /// <summary>
        /// Gets the collection of entity of "ByIdentifier".
        /// </summary>
        /// <param name="request">The request.</param>
        /// <returns></returns>
        public MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeResponseMessageBuiltIn GetCollectionOfEntityOfByIdentifier(
            MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeRequestMessageUserDefinedOfByIdentifier request)
        {
            return base.Channel.GetCollectionOfEntityOfByIdentifier(request);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult MSBuildExtensionPack.WcfContracts.IBuildEventCodeServiceAsyn.BeginGetCollectionOfEntityOfByIdentifier(MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeRequestMessageUserDefinedOfByIdentifier request, System.AsyncCallback callback, object asyncState)
        {
            return base.Channel.BeginGetCollectionOfEntityOfByIdentifier(request, callback, asyncState);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeResponseMessageBuiltIn MSBuildExtensionPack.WcfContracts.IBuildEventCodeServiceAsyn.EndGetCollectionOfEntityOfByIdentifier(System.IAsyncResult result)
        {
            return base.Channel.EndGetCollectionOfEntityOfByIdentifier(result);
        }

        private System.IAsyncResult OnBeginGetCollectionOfEntityOfByIdentifier(object[] inValues, System.AsyncCallback callback, object asyncState)
        {
            MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeRequestMessageUserDefinedOfByIdentifier request = ((MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeRequestMessageUserDefinedOfByIdentifier )(inValues[0]));
            return ((MSBuildExtensionPack.WcfContracts.IBuildEventCodeServiceAsyn)(this)).BeginGetCollectionOfEntityOfByIdentifier(request, callback, asyncState);
        }

        private object[] OnEndGetCollectionOfEntityOfByIdentifier(System.IAsyncResult result)
        {
            MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeResponseMessageBuiltIn retVal = ((MSBuildExtensionPack.WcfContracts.IBuildEventCodeServiceAsyn)(this)).EndGetCollectionOfEntityOfByIdentifier(result);
            return new object[] {
                    retVal};
        }

        private void OnGetCollectionOfEntityOfByIdentifierCompleted(object state)
        {
            if ((this.GetCollectionOfEntityOfByIdentifierCompleted != null))
            {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetCollectionOfEntityOfByIdentifierCompleted(this, new GetCollectionOfEntityOfByIdentifierCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }

        public void GetCollectionOfEntityOfByIdentifierAsync(MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeRequestMessageUserDefinedOfByIdentifier request)
        {
            this.GetCollectionOfEntityOfByIdentifierAsync(request, null);
        }

        public void GetCollectionOfEntityOfByIdentifierAsync(MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeRequestMessageUserDefinedOfByIdentifier request, object userState)
        {
            if ((this.onBeginGetCollectionOfEntityOfByIdentifierDelegate == null))
            {
                this.onBeginGetCollectionOfEntityOfByIdentifierDelegate = new BeginOperationDelegate(this.OnBeginGetCollectionOfEntityOfByIdentifier);
            }
            if ((this.onEndGetCollectionOfEntityOfByIdentifierDelegate == null))
            {
                this.onEndGetCollectionOfEntityOfByIdentifierDelegate = new EndOperationDelegate(this.OnEndGetCollectionOfEntityOfByIdentifier);
            }
            if ((this.onGetCollectionOfEntityOfByIdentifierCompletedDelegate == null))
            {
                this.onGetCollectionOfEntityOfByIdentifierCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetCollectionOfEntityOfByIdentifierCompleted);
            }
            base.InvokeAsync(this.onBeginGetCollectionOfEntityOfByIdentifierDelegate, new object[] {
                        request}, this.onEndGetCollectionOfEntityOfByIdentifierDelegate, this.onGetCollectionOfEntityOfByIdentifierCompletedDelegate, userState);
        }

        #endregion Query Methods Of EntityOfByIdentifier

        #region Query Methods Of KeyInformationOfByIdentifier

        /// <summary>
        /// Gets the collection of entity of "ByIdentifier".
        /// </summary>
        /// <param name="request">The request.</param>
        /// <returns></returns>
        public MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeResponseMessageBuiltIn.KeyInformation GetCollectionOfKeyInformationOfByIdentifier(
            MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeRequestMessageUserDefinedOfByIdentifier request)
        {
            return base.Channel.GetCollectionOfKeyInformationOfByIdentifier(request);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult MSBuildExtensionPack.WcfContracts.IBuildEventCodeServiceAsyn.BeginGetCollectionOfKeyInformationOfByIdentifier(MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeRequestMessageUserDefinedOfByIdentifier request, System.AsyncCallback callback, object asyncState)
        {
            return base.Channel.BeginGetCollectionOfKeyInformationOfByIdentifier(request, callback, asyncState);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeResponseMessageBuiltIn.KeyInformation MSBuildExtensionPack.WcfContracts.IBuildEventCodeServiceAsyn.EndGetCollectionOfKeyInformationOfByIdentifier(System.IAsyncResult result)
        {
            return base.Channel.EndGetCollectionOfKeyInformationOfByIdentifier(result);
        }

        private System.IAsyncResult OnBeginGetCollectionOfKeyInformationOfByIdentifier(object[] inValues, System.AsyncCallback callback, object asyncState)
        {
            MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeRequestMessageUserDefinedOfByIdentifier request = ((MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeRequestMessageUserDefinedOfByIdentifier )(inValues[0]));
            return ((MSBuildExtensionPack.WcfContracts.IBuildEventCodeServiceAsyn)(this)).BeginGetCollectionOfKeyInformationOfByIdentifier(request, callback, asyncState);
        }

        private object[] OnEndGetCollectionOfKeyInformationOfByIdentifier(System.IAsyncResult result)
        {
            MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeResponseMessageBuiltIn.KeyInformation retVal = ((MSBuildExtensionPack.WcfContracts.IBuildEventCodeServiceAsyn)(this)).EndGetCollectionOfKeyInformationOfByIdentifier(result);
            return new object[] {
                    retVal};
        }

        private void OnGetCollectionOfKeyInformationOfByIdentifierCompleted(object state)
        {
            if ((this.GetCollectionOfKeyInformationOfByIdentifierCompleted != null))
            {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetCollectionOfKeyInformationOfByIdentifierCompleted(this, new GetCollectionOfKeyInformationOfByIdentifierCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }

        public void GetCollectionOfKeyInformationOfByIdentifierAsync(MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeRequestMessageUserDefinedOfByIdentifier request)
        {
            this.GetCollectionOfKeyInformationOfByIdentifierAsync(request, null);
        }

        public void GetCollectionOfKeyInformationOfByIdentifierAsync(MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeRequestMessageUserDefinedOfByIdentifier request, object userState)
        {
            if ((this.onBeginGetCollectionOfKeyInformationOfByIdentifierDelegate == null))
            {
                this.onBeginGetCollectionOfKeyInformationOfByIdentifierDelegate = new BeginOperationDelegate(this.OnBeginGetCollectionOfKeyInformationOfByIdentifier);
            }
            if ((this.onEndGetCollectionOfKeyInformationOfByIdentifierDelegate == null))
            {
                this.onEndGetCollectionOfKeyInformationOfByIdentifierDelegate = new EndOperationDelegate(this.OnEndGetCollectionOfKeyInformationOfByIdentifier);
            }
            if ((this.onGetCollectionOfKeyInformationOfByIdentifierCompletedDelegate == null))
            {
                this.onGetCollectionOfKeyInformationOfByIdentifierCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetCollectionOfKeyInformationOfByIdentifierCompleted);
            }
            base.InvokeAsync(this.onBeginGetCollectionOfKeyInformationOfByIdentifierDelegate, new object[] {
                        request}, this.onEndGetCollectionOfKeyInformationOfByIdentifierDelegate, this.onGetCollectionOfKeyInformationOfByIdentifierCompletedDelegate, userState);
        }

        #endregion Query Methods Of KeyInformationOfByIdentifier

        // DataQueryPerQuerySettingCollection -- InClient -- End

        #region GetAscendantAndDescendant

        #endregion GetAscendantAndDescendant

        #region Open and Close

        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState)
        {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }

        private object[] OnEndOpen(System.IAsyncResult result)
        {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }

        private void OnOpenCompleted(object state)
        {
            if ((this.OpenCompleted != null))
            {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }

        public void OpenAsync()
        {
            this.OpenAsync(null);
        }

        public void OpenAsync(object userState)
        {
            if ((this.onBeginOpenDelegate == null))
            {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null))
            {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null))
            {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }

        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState)
        {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }

        private object[] OnEndClose(System.IAsyncResult result)
        {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }

        private void OnCloseCompleted(object state)
        {
            if ((this.CloseCompleted != null))
            {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }

        public void CloseAsync()
        {
            this.CloseAsync(null);
        }

        public void CloseAsync(object userState)
        {
            if ((this.onBeginCloseDelegate == null))
            {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null))
            {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null))
            {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }

        #endregion Open and Close

#if WINDOWS_PHONE

        protected override MSBuildExtensionPack.WcfContracts.IBuildEventCodeServiceAsyn CreateChannel()
        {
            return new WcfClientEntityAsynBuildEventCodeChannel(this);
        }

        private class WcfClientEntityAsynBuildEventCodeChannel : ChannelBase<MSBuildExtensionPack.WcfContracts.IBuildEventCodeServiceAsyn>, MSBuildExtensionPack.WcfContracts.IBuildEventCodeServiceAsyn
        {

            #region constructor

            public WcfClientEntityAsynBuildEventCodeChannel(System.ServiceModel.ClientBase<MSBuildExtensionPack.WcfContracts.IBuildEventCodeServiceAsyn> client) :
                base(client)
            {
            }

            #endregion constructor

            #region Framework.DAL.DataAccessLayerContractBase<MSBuildExtensionPack.DataSourceEntities.BuildEventCodeCollection,MSBuildExtensionPack.DataSourceEntities.BuildEventCode,MSBuildExtensionPack.DataSourceEntities.BuildEventCodeIdentifier> Members

            public System.IAsyncResult BeginInsertEntity(MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeRequestMessageBuiltIn input, System.AsyncCallback callback, object asyncState)
            {
                object[] _args = new object[1];
                _args[0] = input;
                System.IAsyncResult _result = base.BeginInvoke("InsertEntity", _args, callback, asyncState);
                return _result;
            }

            public MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeResponseMessageBuiltIn EndInsertEntity(System.IAsyncResult result)
            {
                object[] _args = new object[0];
                MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeResponseMessageBuiltIn _result = ((MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeResponseMessageBuiltIn)(base.EndInvoke("InsertEntity", _args, result)));
                return _result;
            }

            public System.IAsyncResult BeginUpdateEntity(MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeRequestMessageBuiltIn input, System.AsyncCallback callback, object asyncState)
            {
                object[] _args = new object[1];
                _args[0] = input;
                System.IAsyncResult _result = base.BeginInvoke("UpdateEntity", _args, callback, asyncState);
                return _result;
            }

            public MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeResponseMessageBuiltIn EndUpdateEntity(System.IAsyncResult result)
            {
                object[] _args = new object[0];
                MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeResponseMessageBuiltIn _result = ((MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeResponseMessageBuiltIn)(base.EndInvoke("UpdateEntity", _args, result)));
                return _result;
            }

            public System.IAsyncResult BeginDeleteEntity(MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeRequestMessageBuiltIn input, System.AsyncCallback callback, object asyncState)
            {
                object[] _args = new object[1];
                _args[0] = input;
                System.IAsyncResult _result = base.BeginInvoke("DeleteEntity", _args, callback, asyncState);
                return _result;
            }

            public MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeResponseMessageBuiltIn EndDeleteEntity(System.IAsyncResult result)
            {
                object[] _args = new object[0];
                MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeResponseMessageBuiltIn _result = ((MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeResponseMessageBuiltIn)(base.EndInvoke("DeleteEntity", _args, result)));
                return _result;
            }

            public System.IAsyncResult BeginDeleteByIdentifierEntity(MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeRequestMessageBuiltInOfIdentifier id, System.AsyncCallback callback, object asyncState)
            {
                object[] _args = new object[1];
                _args[0] = id;
                System.IAsyncResult _result = base.BeginInvoke("DeleteByIdentifierEntity", _args, callback, asyncState);
                return _result;
            }

            public MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeResponseMessageBuiltIn EndDeleteByIdentifierEntity(System.IAsyncResult result)
            {
                object[] _args = new object[0];
                MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeResponseMessageBuiltIn _result = ((MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeResponseMessageBuiltIn)(base.EndInvoke("DeleteByIdentifierEntity", _args, result)));
                return _result;
            }

            public System.IAsyncResult BeginBatchInsert(MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeRequestMessageBuiltIn input, System.AsyncCallback callback, object asyncState)
            {
                object[] _args = new object[1];
                _args[0] = input;
                System.IAsyncResult _result = base.BeginInvoke("BatchInsert", _args, callback, asyncState);
                return _result;
            }

            public MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeResponseMessageBuiltIn EndBatchInsert(System.IAsyncResult result)
            {
                object[] _args = new object[0];
                MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeResponseMessageBuiltIn _result = ((MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeResponseMessageBuiltIn)(base.EndInvoke("BatchInsert", _args, result)));
                return _result;
            }

            public System.IAsyncResult BeginBatchDelete(MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeRequestMessageBuiltIn input, System.AsyncCallback callback, object asyncState)
            {
                object[] _args = new object[1];
                _args[0] = input;
                System.IAsyncResult _result = base.BeginInvoke("BatchDelete", _args, callback, asyncState);
                return _result;
            }

            public MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeResponseMessageBuiltIn EndBatchDelete(System.IAsyncResult result)
            {
                object[] _args = new object[0];
                MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeResponseMessageBuiltIn _result = ((MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeResponseMessageBuiltIn)(base.EndInvoke("BatchDelete", _args, result)));
                return _result;
            }

            public System.IAsyncResult BeginBatchUpdate(MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeRequestMessageBuiltIn input, System.AsyncCallback callback, object asyncState)
            {
                object[] _args = new object[1];
                _args[0] = input;
                System.IAsyncResult _result = base.BeginInvoke("BatchUpdate", _args, callback, asyncState);
                return _result;
            }

            public MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeResponseMessageBuiltIn EndBatchUpdate(System.IAsyncResult result)
            {
                object[] _args = new object[0];
                MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeResponseMessageBuiltIn _result = ((MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeResponseMessageBuiltIn)(base.EndInvoke("BatchUpdate", _args, result)));
                return _result;
            }

            #endregion Framework.DAL.DataAccessLayerContractBase<MSBuildExtensionPack.DataSourceEntities.BuildEventCodeCollection,MSBuildExtensionPack.DataSourceEntities.BuildEventCode,MSBuildExtensionPack.DataSourceEntities.BuildEventCodeIdentifier> Members

        #region Binary Columns

        #endregion Binary Columns

            // DataQueryPerQuerySettingCollection -- InChannelForWINDOWS_PHONE -- Start

        #region Query Methods Of EntityOfCommon

            public System.IAsyncResult BeginGetCollectionOfEntityOfCommon(MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeRequestMessageUserDefinedOfCommon request, System.AsyncCallback callback, object asyncState)
            {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("GetCollectionOfEntityOfCommon", _args, callback, asyncState);
                return _result;
            }

            public MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeResponseMessageBuiltIn EndGetCollectionOfEntityOfCommon(System.IAsyncResult result)
            {
                object[] _args = new object[0];
                MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeResponseMessageBuiltIn _result = ((MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeResponseMessageBuiltIn)(base.EndInvoke("GetCollectionOfEntityOfCommon", _args, result)));
                return _result;
            }

        #endregion Query Methods Of EntityOfCommon

        #region Query Methods Of NameValuePairOfAll

            public System.IAsyncResult BeginGetCollectionOfNameValuePairOfAll(MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeRequestMessageUserDefinedOfAll request, System.AsyncCallback callback, object asyncState)
            {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("GetCollectionOfNameValuePairOfAll", _args, callback, asyncState);
                return _result;
            }

            public Framework.CommonBLLEntities.BusinessLogicLayerResponseMessageNameValuePairCollection EndGetCollectionOfNameValuePairOfAll(System.IAsyncResult result)
            {
                object[] _args = new object[0];
                Framework.CommonBLLEntities.BusinessLogicLayerResponseMessageNameValuePairCollection _result = ((Framework.CommonBLLEntities.BusinessLogicLayerResponseMessageNameValuePairCollection)(base.EndInvoke("GetCollectionOfNameValuePairOfAll", _args, result)));
                return _result;
            }

        #endregion Query Methods Of NameValuePairOfAll

        #region Query Methods Of RssItemOfAll

            public System.IAsyncResult BeginGetCollectionOfRssItemOfAll(MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeRequestMessageUserDefinedOfAll request, System.AsyncCallback callback, object asyncState)
            {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("GetCollectionOfRssItemOfAll", _args, callback, asyncState);
                return _result;
            }

            public Framework.CommonBLLEntities.BusinessLogicLayerResponseMessageRssItemCollection EndGetCollectionOfRssItemOfAll(System.IAsyncResult result)
            {
                object[] _args = new object[0];
                Framework.CommonBLLEntities.BusinessLogicLayerResponseMessageRssItemCollection _result = ((Framework.CommonBLLEntities.BusinessLogicLayerResponseMessageRssItemCollection)(base.EndInvoke("GetCollectionOfRssItemOfAll", _args, result)));
                return _result;
            }

        #endregion Query Methods Of RssItemOfAll

        #region Query Methods Of EntityOfByIdentifier

            public System.IAsyncResult BeginGetCollectionOfEntityOfByIdentifier(MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeRequestMessageUserDefinedOfByIdentifier request, System.AsyncCallback callback, object asyncState)
            {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("GetCollectionOfEntityOfByIdentifier", _args, callback, asyncState);
                return _result;
            }

            public MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeResponseMessageBuiltIn EndGetCollectionOfEntityOfByIdentifier(System.IAsyncResult result)
            {
                object[] _args = new object[0];
                MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeResponseMessageBuiltIn _result = ((MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeResponseMessageBuiltIn)(base.EndInvoke("GetCollectionOfEntityOfByIdentifier", _args, result)));
                return _result;
            }

        #endregion Query Methods Of EntityOfByIdentifier

        #region Query Methods Of KeyInformationOfByIdentifier

            public System.IAsyncResult BeginGetCollectionOfKeyInformationOfByIdentifier(MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeRequestMessageUserDefinedOfByIdentifier request, System.AsyncCallback callback, object asyncState)
            {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("GetCollectionOfKeyInformationOfByIdentifier", _args, callback, asyncState);
                return _result;
            }

            public MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeResponseMessageBuiltIn.KeyInformation EndGetCollectionOfKeyInformationOfByIdentifier(System.IAsyncResult result)
            {
                object[] _args = new object[0];
                MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeResponseMessageBuiltIn.KeyInformation _result = ((MSBuildExtensionPack.CommonBLLEntities.BuildEventCodeResponseMessageBuiltIn.KeyInformation)(base.EndInvoke("GetCollectionOfKeyInformationOfByIdentifier", _args, result)));
                return _result;
            }

        #endregion Query Methods Of KeyInformationOfByIdentifier

            // DataQueryPerQuerySettingCollection -- InChannelForWINDOWS_PHONE -- End

            #region GetAscendantAndDescendant

            #endregion GetAscendantAndDescendant

        }
#endif

    }
}

