//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSBuildExtensionPack.Resx {
    using System;
    using System.Reflection;

    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UIStringResourcePerEntitySolution {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public UIStringResourcePerEntitySolution() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MSBuildExtensionPack.Resx.UIStringResourcePerEntitySolution", typeof(UIStringResourcePerEntitySolution).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Solution"".
        /// </summary>
        public static string Solution {
            get {
                return ResourceManager.GetString("Solution", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Loading Solution ..."".
        /// </summary>
        public static string Loading_Solution____ {
            get {
                return ResourceManager.GetString("Loading_Solution____", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Please select Solution ..."".
        /// </summary>
        public static string Please_select_Solution____ {
            get {
                return ResourceManager.GetString("Please_select_Solution____", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Rss Title of Solution"".
        /// </summary>
        public static string Rss_Title_of_Solution {
            get {
                return ResourceManager.GetString("Rss_Title_of_Solution", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Rss Description of Solution"".
        /// </summary>
        public static string Rss_Description_of_Solution {
            get {
                return ResourceManager.GetString("Rss_Description_of_Solution", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "AddNew Solution"".
        /// </summary>
        public static string AddNew_Solution {
            get {
                return ResourceManager.GetString("AddNew_Solution", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Delete Solution"".
        /// </summary>
        public static string Delete_Solution {
            get {
                return ResourceManager.GetString("Delete_Solution", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Details Solution"".
        /// </summary>
        public static string Details_Solution {
            get {
                return ResourceManager.GetString("Details_Solution", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Edit Solution"".
        /// </summary>
        public static string Edit_Solution {
            get {
                return ResourceManager.GetString("Edit_Solution", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Id"".
        /// </summary>
        public static string IdDescription {
            get {
                return ResourceManager.GetString("IdDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Id"".
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Id is required"".
        /// </summary>
        public static string IdRequiredErrorMessage {
            get {
                return ResourceManager.GetString("IdRequiredErrorMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Id"".
        /// </summary>
        public static string IdToolTip {
            get {
                return ResourceManager.GetString("IdToolTip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Id has validation error"".
        /// </summary>
        public static string IdValueValidationErrorMessage {
            get {
                return ResourceManager.GetString("IdValueValidationErrorMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Please input Id validation regular expression"".
        /// </summary>
        public static string IdValueValidationExpression {
            get {
                return ResourceManager.GetString("IdValueValidationExpression", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Id is required"".
        /// </summary>
        public static string Id_is_required {
            get {
                return ResourceManager.GetString("Id_is_required", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "External Parent Id"".
        /// </summary>
        public static string ExternalParentIdDescription {
            get {
                return ResourceManager.GetString("ExternalParentIdDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "External Parent Id"".
        /// </summary>
        public static string ExternalParentId {
            get {
                return ResourceManager.GetString("ExternalParentId", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "External Parent Id is required"".
        /// </summary>
        public static string ExternalParentIdRequiredErrorMessage {
            get {
                return ResourceManager.GetString("ExternalParentIdRequiredErrorMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "External Parent Id"".
        /// </summary>
        public static string ExternalParentIdToolTip {
            get {
                return ResourceManager.GetString("ExternalParentIdToolTip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "External Parent Id has validation error"".
        /// </summary>
        public static string ExternalParentIdValueValidationErrorMessage {
            get {
                return ResourceManager.GetString("ExternalParentIdValueValidationErrorMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Please input External Parent Id validation regular expression"".
        /// </summary>
        public static string ExternalParentIdValueValidationExpression {
            get {
                return ResourceManager.GetString("ExternalParentIdValueValidationExpression", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "The length of ExternalParentId should be 0 to 100"".
        /// </summary>
        public static string The_length_of_ExternalParentId_should_be_0_to_100 {
            get {
                return ResourceManager.GetString("The_length_of_ExternalParentId_should_be_0_to_100", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Name"".
        /// </summary>
        public static string NameDescription {
            get {
                return ResourceManager.GetString("NameDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Name"".
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Name is required"".
        /// </summary>
        public static string NameRequiredErrorMessage {
            get {
                return ResourceManager.GetString("NameRequiredErrorMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Name"".
        /// </summary>
        public static string NameToolTip {
            get {
                return ResourceManager.GetString("NameToolTip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Name has validation error"".
        /// </summary>
        public static string NameValueValidationErrorMessage {
            get {
                return ResourceManager.GetString("NameValueValidationErrorMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Please input Name validation regular expression"".
        /// </summary>
        public static string NameValueValidationExpression {
            get {
                return ResourceManager.GetString("NameValueValidationExpression", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Name is required"".
        /// </summary>
        public static string Name_is_required {
            get {
                return ResourceManager.GetString("Name_is_required", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "The length of Name should be 0 to 100"".
        /// </summary>
        public static string The_length_of_Name_should_be_0_to_100 {
            get {
                return ResourceManager.GetString("The_length_of_Name_should_be_0_to_100", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Description"".
        /// </summary>
        public static string DescriptionDescription {
            get {
                return ResourceManager.GetString("DescriptionDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Description"".
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Description is required"".
        /// </summary>
        public static string DescriptionRequiredErrorMessage {
            get {
                return ResourceManager.GetString("DescriptionRequiredErrorMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Description"".
        /// </summary>
        public static string DescriptionToolTip {
            get {
                return ResourceManager.GetString("DescriptionToolTip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Description has validation error"".
        /// </summary>
        public static string DescriptionValueValidationErrorMessage {
            get {
                return ResourceManager.GetString("DescriptionValueValidationErrorMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Please input Description validation regular expression"".
        /// </summary>
        public static string DescriptionValueValidationExpression {
            get {
                return ResourceManager.GetString("DescriptionValueValidationExpression", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "The length of Description should be 0 to 1500"".
        /// </summary>
        public static string The_length_of_Description_should_be_0_to_1500 {
            get {
                return ResourceManager.GetString("The_length_of_Description_should_be_0_to_1500", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Organization Id"".
        /// </summary>
        public static string OrganizationIdDescription {
            get {
                return ResourceManager.GetString("OrganizationIdDescription", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Organization Id"".
        /// </summary>
        public static string OrganizationId {
            get {
                return ResourceManager.GetString("OrganizationId", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Organization Id is required"".
        /// </summary>
        public static string OrganizationIdRequiredErrorMessage {
            get {
                return ResourceManager.GetString("OrganizationIdRequiredErrorMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Organization Id"".
        /// </summary>
        public static string OrganizationIdToolTip {
            get {
                return ResourceManager.GetString("OrganizationIdToolTip", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Organization Id has validation error"".
        /// </summary>
        public static string OrganizationIdValueValidationErrorMessage {
            get {
                return ResourceManager.GetString("OrganizationIdValueValidationErrorMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Please input Organization Id validation regular expression"".
        /// </summary>
        public static string OrganizationIdValueValidationExpression {
            get {
                return ResourceManager.GetString("OrganizationIdValueValidationExpression", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Organization"".
        /// </summary>
        public static string Organization_1_UniqueIdentifier {
            get {
                return ResourceManager.GetString("Organization_1_UniqueIdentifier", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Required Field Error Message of property Organization_1_UniqueIdentifier of MSBuildExtensionPack.Solution"".
        /// </summary>
        public static string Required_Field_Error_Message_of_property_Organization_1_UniqueIdentifier_of_MSBuildExtensionPack_Solution {
            get {
                return ResourceManager.GetString("Required_Field_Error_Message_of_property_Organization_1_UniqueIdentifier_of_MSBuildExtensionPack_Solution", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Value Validation Error Message of property Organization_1_UniqueIdentifier of MSBuildExtensionPack.Solution"".
        /// </summary>
        public static string Value_Validation_Error_Message_of_property_Organization_1_UniqueIdentifier_of_MSBuildExtensionPack_Solution {
            get {
                return ResourceManager.GetString("Value_Validation_Error_Message_of_property_Organization_1_UniqueIdentifier_of_MSBuildExtensionPack_Solution", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Organization"".
        /// </summary>
        public static string Organization_1_Name {
            get {
                return ResourceManager.GetString("Organization_1_Name", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Required Field Error Message of property Organization_1_Name of MSBuildExtensionPack.Solution"".
        /// </summary>
        public static string Required_Field_Error_Message_of_property_Organization_1_Name_of_MSBuildExtensionPack_Solution {
            get {
                return ResourceManager.GetString("Required_Field_Error_Message_of_property_Organization_1_Name_of_MSBuildExtensionPack_Solution", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Value Validation Error Message of property Organization_1_Name of MSBuildExtensionPack.Solution"".
        /// </summary>
        public static string Value_Validation_Error_Message_of_property_Organization_1_Name_of_MSBuildExtensionPack_Solution {
            get {
                return ResourceManager.GetString("Value_Validation_Error_Message_of_property_Organization_1_Name_of_MSBuildExtensionPack_Solution", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Required Field Error Message of property Id of MSBuildExtensionPack.Solution"".
        /// </summary>
        public static string Required_Field_Error_Message_of_property_Id_of_MSBuildExtensionPack_Solution {
            get {
                return ResourceManager.GetString("Required_Field_Error_Message_of_property_Id_of_MSBuildExtensionPack_Solution", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Value Validation Error Message of property Id of MSBuildExtensionPack.Solution"".
        /// </summary>
        public static string Value_Validation_Error_Message_of_property_Id_of_MSBuildExtensionPack_Solution {
            get {
                return ResourceManager.GetString("Value_Validation_Error_Message_of_property_Id_of_MSBuildExtensionPack_Solution", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Organization"".
        /// </summary>
        public static string Organization_2Id {
            get {
                return ResourceManager.GetString("Organization_2Id", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Required Field Error Message of property Organization_2Id of MSBuildExtensionPack.Solution"".
        /// </summary>
        public static string Required_Field_Error_Message_of_property_Organization_2Id_of_MSBuildExtensionPack_Solution {
            get {
                return ResourceManager.GetString("Required_Field_Error_Message_of_property_Organization_2Id_of_MSBuildExtensionPack_Solution", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Value Validation Error Message of property Organization_2Id of MSBuildExtensionPack.Solution"".
        /// </summary>
        public static string Value_Validation_Error_Message_of_property_Organization_2Id_of_MSBuildExtensionPack_Solution {
            get {
                return ResourceManager.GetString("Value_Validation_Error_Message_of_property_Organization_2Id_of_MSBuildExtensionPack_Solution", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Organization"".
        /// </summary>
        public static string Organization_2_UniqueIdentifier {
            get {
                return ResourceManager.GetString("Organization_2_UniqueIdentifier", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Required Field Error Message of property Organization_2_UniqueIdentifier of MSBuildExtensionPack.Solution"".
        /// </summary>
        public static string Required_Field_Error_Message_of_property_Organization_2_UniqueIdentifier_of_MSBuildExtensionPack_Solution {
            get {
                return ResourceManager.GetString("Required_Field_Error_Message_of_property_Organization_2_UniqueIdentifier_of_MSBuildExtensionPack_Solution", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Value Validation Error Message of property Organization_2_UniqueIdentifier of MSBuildExtensionPack.Solution"".
        /// </summary>
        public static string Value_Validation_Error_Message_of_property_Organization_2_UniqueIdentifier_of_MSBuildExtensionPack_Solution {
            get {
                return ResourceManager.GetString("Value_Validation_Error_Message_of_property_Organization_2_UniqueIdentifier_of_MSBuildExtensionPack_Solution", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Organization"".
        /// </summary>
        public static string Organization_2_Name {
            get {
                return ResourceManager.GetString("Organization_2_Name", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Required Field Error Message of property Organization_2_Name of MSBuildExtensionPack.Solution"".
        /// </summary>
        public static string Required_Field_Error_Message_of_property_Organization_2_Name_of_MSBuildExtensionPack_Solution {
            get {
                return ResourceManager.GetString("Required_Field_Error_Message_of_property_Organization_2_Name_of_MSBuildExtensionPack_Solution", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Value Validation Error Message of property Organization_2_Name of MSBuildExtensionPack.Solution"".
        /// </summary>
        public static string Value_Validation_Error_Message_of_property_Organization_2_Name_of_MSBuildExtensionPack_Solution {
            get {
                return ResourceManager.GetString("Value_Validation_Error_Message_of_property_Organization_2_Name_of_MSBuildExtensionPack_Solution", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Required Field Error Message of property ExternalParentId of MSBuildExtensionPack.Solution"".
        /// </summary>
        public static string Required_Field_Error_Message_of_property_ExternalParentId_of_MSBuildExtensionPack_Solution {
            get {
                return ResourceManager.GetString("Required_Field_Error_Message_of_property_ExternalParentId_of_MSBuildExtensionPack_Solution", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Value Validation Error Message of property ExternalParentId of MSBuildExtensionPack.Solution"".
        /// </summary>
        public static string Value_Validation_Error_Message_of_property_ExternalParentId_of_MSBuildExtensionPack_Solution {
            get {
                return ResourceManager.GetString("Value_Validation_Error_Message_of_property_ExternalParentId_of_MSBuildExtensionPack_Solution", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Required Field Error Message of property Name of MSBuildExtensionPack.Solution"".
        /// </summary>
        public static string Required_Field_Error_Message_of_property_Name_of_MSBuildExtensionPack_Solution {
            get {
                return ResourceManager.GetString("Required_Field_Error_Message_of_property_Name_of_MSBuildExtensionPack_Solution", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Value Validation Error Message of property Name of MSBuildExtensionPack.Solution"".
        /// </summary>
        public static string Value_Validation_Error_Message_of_property_Name_of_MSBuildExtensionPack_Solution {
            get {
                return ResourceManager.GetString("Value_Validation_Error_Message_of_property_Name_of_MSBuildExtensionPack_Solution", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Required Field Error Message of property Description of MSBuildExtensionPack.Solution"".
        /// </summary>
        public static string Required_Field_Error_Message_of_property_Description_of_MSBuildExtensionPack_Solution {
            get {
                return ResourceManager.GetString("Required_Field_Error_Message_of_property_Description_of_MSBuildExtensionPack_Solution", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Value Validation Error Message of property Description of MSBuildExtensionPack.Solution"".
        /// </summary>
        public static string Value_Validation_Error_Message_of_property_Description_of_MSBuildExtensionPack_Solution {
            get {
                return ResourceManager.GetString("Value_Validation_Error_Message_of_property_Description_of_MSBuildExtensionPack_Solution", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Required Field Error Message of property OrganizationId of MSBuildExtensionPack.Solution"".
        /// </summary>
        public static string Required_Field_Error_Message_of_property_OrganizationId_of_MSBuildExtensionPack_Solution {
            get {
                return ResourceManager.GetString("Required_Field_Error_Message_of_property_OrganizationId_of_MSBuildExtensionPack_Solution", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Value Validation Error Message of property OrganizationId of MSBuildExtensionPack.Solution"".
        /// </summary>
        public static string Value_Validation_Error_Message_of_property_OrganizationId_of_MSBuildExtensionPack_Solution {
            get {
                return ResourceManager.GetString("Value_Validation_Error_Message_of_property_OrganizationId_of_MSBuildExtensionPack_Solution", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "CountPerFK"".
        /// </summary>
        public static string CountPerFK {
            get {
                return ResourceManager.GetString("CountPerFK", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Required Field Error Message of property CountPerFK of MSBuildExtensionPack.Solution"".
        /// </summary>
        public static string Required_Field_Error_Message_of_property_CountPerFK_of_MSBuildExtensionPack_Solution {
            get {
                return ResourceManager.GetString("Required_Field_Error_Message_of_property_CountPerFK_of_MSBuildExtensionPack_Solution", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Value Validation Error Message of property CountPerFK of MSBuildExtensionPack.Solution"".
        /// </summary>
        public static string Value_Validation_Error_Message_of_property_CountPerFK_of_MSBuildExtensionPack_Solution {
            get {
                return ResourceManager.GetString("Value_Validation_Error_Message_of_property_CountPerFK_of_MSBuildExtensionPack_Solution", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Value"".
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Required Field Error Message of property Value of MSBuildExtensionPack.Solution"".
        /// </summary>
        public static string Required_Field_Error_Message_of_property_Value_of_MSBuildExtensionPack_Solution {
            get {
                return ResourceManager.GetString("Required_Field_Error_Message_of_property_Value_of_MSBuildExtensionPack_Solution", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Value Validation Error Message of property Value of MSBuildExtensionPack.Solution"".
        /// </summary>
        public static string Value_Validation_Error_Message_of_property_Value_of_MSBuildExtensionPack_Solution {
            get {
                return ResourceManager.GetString("Value_Validation_Error_Message_of_property_Value_of_MSBuildExtensionPack_Solution", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "IdentifierInString"".
        /// </summary>
        public static string IdentifierInString {
            get {
                return ResourceManager.GetString("IdentifierInString", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Required Field Error Message of property IdentifierInString of MSBuildExtensionPack.Solution"".
        /// </summary>
        public static string Required_Field_Error_Message_of_property_IdentifierInString_of_MSBuildExtensionPack_Solution {
            get {
                return ResourceManager.GetString("Required_Field_Error_Message_of_property_IdentifierInString_of_MSBuildExtensionPack_Solution", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Value Validation Error Message of property IdentifierInString of MSBuildExtensionPack.Solution"".
        /// </summary>
        public static string Value_Validation_Error_Message_of_property_IdentifierInString_of_MSBuildExtensionPack_Solution {
            get {
                return ResourceManager.GetString("Value_Validation_Error_Message_of_property_IdentifierInString_of_MSBuildExtensionPack_Solution", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Title"".
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Required Field Error Message of property Title of MSBuildExtensionPack.Solution"".
        /// </summary>
        public static string Required_Field_Error_Message_of_property_Title_of_MSBuildExtensionPack_Solution {
            get {
                return ResourceManager.GetString("Required_Field_Error_Message_of_property_Title_of_MSBuildExtensionPack_Solution", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Value Validation Error Message of property Title of MSBuildExtensionPack.Solution"".
        /// </summary>
        public static string Value_Validation_Error_Message_of_property_Title_of_MSBuildExtensionPack_Solution {
            get {
                return ResourceManager.GetString("Value_Validation_Error_Message_of_property_Title_of_MSBuildExtensionPack_Solution", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Organization"".
        /// </summary>
        public static string IsToCompare_ID_CheckBox_Search_isToCompareIdCommonOfOrganization_1OfCommon {
            get {
                return ResourceManager.GetString("IsToCompare_ID_CheckBox_Search_isToCompareIdCommonOfOrganization_1OfCommon", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Description of Id of Organization"".
        /// </summary>
        public static string Description_of_IsToCompare_ID_CheckBox_Search_isToCompareIdCommonOfOrganization_1OfCommon {
            get {
                return ResourceManager.GetString("Description_of_IsToCompare_ID_CheckBox_Search_isToCompareIdCommonOfOrganization_1OfCommon", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Tooltip of Id of Organization"".
        /// </summary>
        public static string Tooltip_of_IsToCompare_ID_CheckBox_Search_isToCompareIdCommonOfOrganization_1OfCommon {
            get {
                return ResourceManager.GetString("Tooltip_of_IsToCompare_ID_CheckBox_Search_isToCompareIdCommonOfOrganization_1OfCommon", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Id of Organization"".
        /// </summary>
        public static string ValueToCompare_ID_DropDownList_Search_valueToCompareIdCommonOfOrganization_1OfCommon {
            get {
                return ResourceManager.GetString("ValueToCompare_ID_DropDownList_Search_valueToCompareIdCommonOfOrganization_1OfCommon", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Description of Id of Organization"".
        /// </summary>
        public static string Description_of_ValueToCompare_ID_DropDownList_Search_valueToCompareIdCommonOfOrganization_1OfCommon {
            get {
                return ResourceManager.GetString("Description_of_ValueToCompare_ID_DropDownList_Search_valueToCompareIdCommonOfOrganization_1OfCommon", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Tooltip of Id of Organization"".
        /// </summary>
        public static string Tooltip_of_ValueToCompare_ID_DropDownList_Search_valueToCompareIdCommonOfOrganization_1OfCommon {
            get {
                return ResourceManager.GetString("Tooltip_of_ValueToCompare_ID_DropDownList_Search_valueToCompareIdCommonOfOrganization_1OfCommon", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Organization"".
        /// </summary>
        public static string IsToCompare_ID_CheckBox_Search_isToCompareIdCommonOfOrganization_2OfCommon {
            get {
                return ResourceManager.GetString("IsToCompare_ID_CheckBox_Search_isToCompareIdCommonOfOrganization_2OfCommon", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Description of Id of Organization"".
        /// </summary>
        public static string Description_of_IsToCompare_ID_CheckBox_Search_isToCompareIdCommonOfOrganization_2OfCommon {
            get {
                return ResourceManager.GetString("Description_of_IsToCompare_ID_CheckBox_Search_isToCompareIdCommonOfOrganization_2OfCommon", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Tooltip of Id of Organization"".
        /// </summary>
        public static string Tooltip_of_IsToCompare_ID_CheckBox_Search_isToCompareIdCommonOfOrganization_2OfCommon {
            get {
                return ResourceManager.GetString("Tooltip_of_IsToCompare_ID_CheckBox_Search_isToCompareIdCommonOfOrganization_2OfCommon", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Id of Organization"".
        /// </summary>
        public static string ValueToCompare_ID_DropDownList_Search_valueToCompareIdCommonOfOrganization_2OfCommon {
            get {
                return ResourceManager.GetString("ValueToCompare_ID_DropDownList_Search_valueToCompareIdCommonOfOrganization_2OfCommon", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Description of Id of Organization"".
        /// </summary>
        public static string Description_of_ValueToCompare_ID_DropDownList_Search_valueToCompareIdCommonOfOrganization_2OfCommon {
            get {
                return ResourceManager.GetString("Description_of_ValueToCompare_ID_DropDownList_Search_valueToCompareIdCommonOfOrganization_2OfCommon", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Tooltip of Id of Organization"".
        /// </summary>
        public static string Tooltip_of_ValueToCompare_ID_DropDownList_Search_valueToCompareIdCommonOfOrganization_2OfCommon {
            get {
                return ResourceManager.GetString("Tooltip_of_ValueToCompare_ID_DropDownList_Search_valueToCompareIdCommonOfOrganization_2OfCommon", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "ExternalParentId"".
        /// </summary>
        public static string IsToCompare_ID_CheckBox_Search_isToCompareExternalParentIdCommonOftOfCommon {
            get {
                return ResourceManager.GetString("IsToCompare_ID_CheckBox_Search_isToCompareExternalParentIdCommonOftOfCommon", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Description of ExternalParentId"".
        /// </summary>
        public static string Description_of_IsToCompare_ID_CheckBox_Search_isToCompareExternalParentIdCommonOftOfCommon {
            get {
                return ResourceManager.GetString("Description_of_IsToCompare_ID_CheckBox_Search_isToCompareExternalParentIdCommonOftOfCommon", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Tooltip of ExternalParentId"".
        /// </summary>
        public static string Tooltip_of_IsToCompare_ID_CheckBox_Search_isToCompareExternalParentIdCommonOftOfCommon {
            get {
                return ResourceManager.GetString("Tooltip_of_IsToCompare_ID_CheckBox_Search_isToCompareExternalParentIdCommonOftOfCommon", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "ExternalParentId of Solution"".
        /// </summary>
        public static string ValueToBeContained_ID_TextBox_Search_valueToBeContainedExternalParentIdCommonOftOfCommon {
            get {
                return ResourceManager.GetString("ValueToBeContained_ID_TextBox_Search_valueToBeContainedExternalParentIdCommonOftOfCommon", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Description of ExternalParentId of Solution"".
        /// </summary>
        public static string Description_of_ValueToBeContained_ID_TextBox_Search_valueToBeContainedExternalParentIdCommonOftOfCommon {
            get {
                return ResourceManager.GetString("Description_of_ValueToBeContained_ID_TextBox_Search_valueToBeContainedExternalParentIdCommonOftOfCommon", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Tooltip of ExternalParentId of Solution"".
        /// </summary>
        public static string Tooltip_of_ValueToBeContained_ID_TextBox_Search_valueToBeContainedExternalParentIdCommonOftOfCommon {
            get {
                return ResourceManager.GetString("Tooltip_of_ValueToBeContained_ID_TextBox_Search_valueToBeContainedExternalParentIdCommonOftOfCommon", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Name"".
        /// </summary>
        public static string IsToCompare_ID_CheckBox_Search_isToCompareNameCommonOftOfCommon {
            get {
                return ResourceManager.GetString("IsToCompare_ID_CheckBox_Search_isToCompareNameCommonOftOfCommon", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Description of Name"".
        /// </summary>
        public static string Description_of_IsToCompare_ID_CheckBox_Search_isToCompareNameCommonOftOfCommon {
            get {
                return ResourceManager.GetString("Description_of_IsToCompare_ID_CheckBox_Search_isToCompareNameCommonOftOfCommon", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Tooltip of Name"".
        /// </summary>
        public static string Tooltip_of_IsToCompare_ID_CheckBox_Search_isToCompareNameCommonOftOfCommon {
            get {
                return ResourceManager.GetString("Tooltip_of_IsToCompare_ID_CheckBox_Search_isToCompareNameCommonOftOfCommon", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Name of Solution"".
        /// </summary>
        public static string ValueToBeContained_ID_TextBox_Search_valueToBeContainedNameCommonOftOfCommon {
            get {
                return ResourceManager.GetString("ValueToBeContained_ID_TextBox_Search_valueToBeContainedNameCommonOftOfCommon", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Description of Name of Solution"".
        /// </summary>
        public static string Description_of_ValueToBeContained_ID_TextBox_Search_valueToBeContainedNameCommonOftOfCommon {
            get {
                return ResourceManager.GetString("Description_of_ValueToBeContained_ID_TextBox_Search_valueToBeContainedNameCommonOftOfCommon", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Tooltip of Name of Solution"".
        /// </summary>
        public static string Tooltip_of_ValueToBeContained_ID_TextBox_Search_valueToBeContainedNameCommonOftOfCommon {
            get {
                return ResourceManager.GetString("Tooltip_of_ValueToBeContained_ID_TextBox_Search_valueToBeContainedNameCommonOftOfCommon", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Description"".
        /// </summary>
        public static string IsToCompare_ID_CheckBox_Search_isToCompareDescriptionCommonOftOfCommon {
            get {
                return ResourceManager.GetString("IsToCompare_ID_CheckBox_Search_isToCompareDescriptionCommonOftOfCommon", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Description of Description"".
        /// </summary>
        public static string Description_of_IsToCompare_ID_CheckBox_Search_isToCompareDescriptionCommonOftOfCommon {
            get {
                return ResourceManager.GetString("Description_of_IsToCompare_ID_CheckBox_Search_isToCompareDescriptionCommonOftOfCommon", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Tooltip of Description"".
        /// </summary>
        public static string Tooltip_of_IsToCompare_ID_CheckBox_Search_isToCompareDescriptionCommonOftOfCommon {
            get {
                return ResourceManager.GetString("Tooltip_of_IsToCompare_ID_CheckBox_Search_isToCompareDescriptionCommonOftOfCommon", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Description of Solution"".
        /// </summary>
        public static string ValueToBeContained_ID_TextBox_Search_valueToBeContainedDescriptionCommonOftOfCommon {
            get {
                return ResourceManager.GetString("ValueToBeContained_ID_TextBox_Search_valueToBeContainedDescriptionCommonOftOfCommon", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Description of Description of Solution"".
        /// </summary>
        public static string Description_of_ValueToBeContained_ID_TextBox_Search_valueToBeContainedDescriptionCommonOftOfCommon {
            get {
                return ResourceManager.GetString("Description_of_ValueToBeContained_ID_TextBox_Search_valueToBeContainedDescriptionCommonOftOfCommon", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Tooltip of Description of Solution"".
        /// </summary>
        public static string Tooltip_of_ValueToBeContained_ID_TextBox_Search_valueToBeContainedDescriptionCommonOftOfCommon {
            get {
                return ResourceManager.GetString("Tooltip_of_ValueToBeContained_ID_TextBox_Search_valueToBeContainedDescriptionCommonOftOfCommon", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Organization"".
        /// </summary>
        public static string IsToCompare_ID_CheckBox_Search_isToCompareIdFKOnlyOfOrganization_1OfFKOnly {
            get {
                return ResourceManager.GetString("IsToCompare_ID_CheckBox_Search_isToCompareIdFKOnlyOfOrganization_1OfFKOnly", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Description of Id of Organization"".
        /// </summary>
        public static string Description_of_IsToCompare_ID_CheckBox_Search_isToCompareIdFKOnlyOfOrganization_1OfFKOnly {
            get {
                return ResourceManager.GetString("Description_of_IsToCompare_ID_CheckBox_Search_isToCompareIdFKOnlyOfOrganization_1OfFKOnly", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Tooltip of Id of Organization"".
        /// </summary>
        public static string Tooltip_of_IsToCompare_ID_CheckBox_Search_isToCompareIdFKOnlyOfOrganization_1OfFKOnly {
            get {
                return ResourceManager.GetString("Tooltip_of_IsToCompare_ID_CheckBox_Search_isToCompareIdFKOnlyOfOrganization_1OfFKOnly", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Id of Organization"".
        /// </summary>
        public static string ValueToCompare_ID_DropDownList_Search_valueToCompareIdFKOnlyOfOrganization_1OfFKOnly {
            get {
                return ResourceManager.GetString("ValueToCompare_ID_DropDownList_Search_valueToCompareIdFKOnlyOfOrganization_1OfFKOnly", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Description of Id of Organization"".
        /// </summary>
        public static string Description_of_ValueToCompare_ID_DropDownList_Search_valueToCompareIdFKOnlyOfOrganization_1OfFKOnly {
            get {
                return ResourceManager.GetString("Description_of_ValueToCompare_ID_DropDownList_Search_valueToCompareIdFKOnlyOfOrganization_1OfFKOnly", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Tooltip of Id of Organization"".
        /// </summary>
        public static string Tooltip_of_ValueToCompare_ID_DropDownList_Search_valueToCompareIdFKOnlyOfOrganization_1OfFKOnly {
            get {
                return ResourceManager.GetString("Tooltip_of_ValueToCompare_ID_DropDownList_Search_valueToCompareIdFKOnlyOfOrganization_1OfFKOnly", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Organization"".
        /// </summary>
        public static string IsToCompare_ID_CheckBox_Search_isToCompareIdFKOnlyOfOrganization_2OfFKOnly {
            get {
                return ResourceManager.GetString("IsToCompare_ID_CheckBox_Search_isToCompareIdFKOnlyOfOrganization_2OfFKOnly", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Description of Id of Organization"".
        /// </summary>
        public static string Description_of_IsToCompare_ID_CheckBox_Search_isToCompareIdFKOnlyOfOrganization_2OfFKOnly {
            get {
                return ResourceManager.GetString("Description_of_IsToCompare_ID_CheckBox_Search_isToCompareIdFKOnlyOfOrganization_2OfFKOnly", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Tooltip of Id of Organization"".
        /// </summary>
        public static string Tooltip_of_IsToCompare_ID_CheckBox_Search_isToCompareIdFKOnlyOfOrganization_2OfFKOnly {
            get {
                return ResourceManager.GetString("Tooltip_of_IsToCompare_ID_CheckBox_Search_isToCompareIdFKOnlyOfOrganization_2OfFKOnly", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Id of Organization"".
        /// </summary>
        public static string ValueToCompare_ID_DropDownList_Search_valueToCompareIdFKOnlyOfOrganization_2OfFKOnly {
            get {
                return ResourceManager.GetString("ValueToCompare_ID_DropDownList_Search_valueToCompareIdFKOnlyOfOrganization_2OfFKOnly", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Description of Id of Organization"".
        /// </summary>
        public static string Description_of_ValueToCompare_ID_DropDownList_Search_valueToCompareIdFKOnlyOfOrganization_2OfFKOnly {
            get {
                return ResourceManager.GetString("Description_of_ValueToCompare_ID_DropDownList_Search_valueToCompareIdFKOnlyOfOrganization_2OfFKOnly", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Tooltip of Id of Organization"".
        /// </summary>
        public static string Tooltip_of_ValueToCompare_ID_DropDownList_Search_valueToCompareIdFKOnlyOfOrganization_2OfFKOnly {
            get {
                return ResourceManager.GetString("Tooltip_of_ValueToCompare_ID_DropDownList_Search_valueToCompareIdFKOnlyOfOrganization_2OfFKOnly", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Id"".
        /// </summary>
        public static string IsToCompare_ID_CheckBox_Search_isToCompareIdIdentifierOftOfIdentifier {
            get {
                return ResourceManager.GetString("IsToCompare_ID_CheckBox_Search_isToCompareIdIdentifierOftOfIdentifier", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Description of Id"".
        /// </summary>
        public static string Description_of_IsToCompare_ID_CheckBox_Search_isToCompareIdIdentifierOftOfIdentifier {
            get {
                return ResourceManager.GetString("Description_of_IsToCompare_ID_CheckBox_Search_isToCompareIdIdentifierOftOfIdentifier", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Tooltip of Id"".
        /// </summary>
        public static string Tooltip_of_IsToCompare_ID_CheckBox_Search_isToCompareIdIdentifierOftOfIdentifier {
            get {
                return ResourceManager.GetString("Tooltip_of_IsToCompare_ID_CheckBox_Search_isToCompareIdIdentifierOftOfIdentifier", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Id of Solution"".
        /// </summary>
        public static string ValueToCompare_ID_Unknown_Search_valueToCompareIdIdentifierOftOfIdentifier {
            get {
                return ResourceManager.GetString("ValueToCompare_ID_Unknown_Search_valueToCompareIdIdentifierOftOfIdentifier", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Description of Id of Solution"".
        /// </summary>
        public static string Description_of_ValueToCompare_ID_Unknown_Search_valueToCompareIdIdentifierOftOfIdentifier {
            get {
                return ResourceManager.GetString("Description_of_ValueToCompare_ID_Unknown_Search_valueToCompareIdIdentifierOftOfIdentifier", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Tooltip of Id of Solution"".
        /// </summary>
        public static string Tooltip_of_ValueToCompare_ID_Unknown_Search_valueToCompareIdIdentifierOftOfIdentifier {
            get {
                return ResourceManager.GetString("Tooltip_of_ValueToCompare_ID_Unknown_Search_valueToCompareIdIdentifierOftOfIdentifier", resourceCulture);
            }
        }

    }
}

