//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSBuildExtensionPack.Resx {
    using System;
    using System.Reflection;

    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UIStringResourcePerApp {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public UIStringResourcePerApp() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MSBuildExtensionPack.Resx.UIStringResourcePerApp", typeof(UIStringResourcePerApp).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "MSBuildExtensionPack"".
        /// </summary>
        public static string Application_Title {
            get {
                return ResourceManager.GetString("Application_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Search Build"".
        /// </summary>
        public static string MSBuildExtensionPack_Build_Common_Title {
            get {
                return ResourceManager.GetString("MSBuildExtensionPack_Build_Common_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Search"".
        /// </summary>
        public static string MSBuildExtensionPack_Build_Common_ShortTitle {
            get {
                return ResourceManager.GetString("MSBuildExtensionPack_Build_Common_ShortTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Summary of Build:MSBuildExtensionPack_Build_Common"".
        /// </summary>
        public static string MSBuildExtensionPack_Build_Common_Summary {
            get {
                return ResourceManager.GetString("MSBuildExtensionPack_Build_Common_Summary", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Full Details"".
        /// </summary>
        public static string MSBuildExtensionPack_Build_FullDetails_Title {
            get {
                return ResourceManager.GetString("MSBuildExtensionPack_Build_FullDetails_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Full"".
        /// </summary>
        public static string MSBuildExtensionPack_Build_FullDetails_ShortTitle {
            get {
                return ResourceManager.GetString("MSBuildExtensionPack_Build_FullDetails_ShortTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Summary of Build:MSBuildExtensionPack_Build_FullDetails"".
        /// </summary>
        public static string MSBuildExtensionPack_Build_FullDetails_Summary {
            get {
                return ResourceManager.GetString("MSBuildExtensionPack_Build_FullDetails_Summary", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Common Search View"".
        /// </summary>
        public static string MSBuildExtensionPack_Build_CommonSearchView_Title {
            get {
                return ResourceManager.GetString("MSBuildExtensionPack_Build_CommonSearchView_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Common"".
        /// </summary>
        public static string MSBuildExtensionPack_Build_CommonSearchView_ShortTitle {
            get {
                return ResourceManager.GetString("MSBuildExtensionPack_Build_CommonSearchView_ShortTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Summary of Build:MSBuildExtensionPack_Build_CommonSearchView"".
        /// </summary>
        public static string MSBuildExtensionPack_Build_CommonSearchView_Summary {
            get {
                return ResourceManager.GetString("MSBuildExtensionPack_Build_CommonSearchView_Summary", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Common Result View"".
        /// </summary>
        public static string MSBuildExtensionPack_Build_CommonResultView_Title {
            get {
                return ResourceManager.GetString("MSBuildExtensionPack_Build_CommonResultView_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Common"".
        /// </summary>
        public static string MSBuildExtensionPack_Build_CommonResultView_ShortTitle {
            get {
                return ResourceManager.GetString("MSBuildExtensionPack_Build_CommonResultView_ShortTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Summary of Build:MSBuildExtensionPack_Build_CommonResultView"".
        /// </summary>
        public static string MSBuildExtensionPack_Build_CommonResultView_Summary {
            get {
                return ResourceManager.GetString("MSBuildExtensionPack_Build_CommonResultView_Summary", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Tabbed Common"".
        /// </summary>
        public static string MSBuildExtensionPack_Build_TabbedCommon_Title {
            get {
                return ResourceManager.GetString("MSBuildExtensionPack_Build_TabbedCommon_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Tabbed"".
        /// </summary>
        public static string MSBuildExtensionPack_Build_TabbedCommon_ShortTitle {
            get {
                return ResourceManager.GetString("MSBuildExtensionPack_Build_TabbedCommon_ShortTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Summary of Build:MSBuildExtensionPack_Build_TabbedCommon"".
        /// </summary>
        public static string MSBuildExtensionPack_Build_TabbedCommon_Summary {
            get {
                return ResourceManager.GetString("MSBuildExtensionPack_Build_TabbedCommon_Summary", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Search BuildEventCode"".
        /// </summary>
        public static string MSBuildExtensionPack_BuildEventCode_Common_Title {
            get {
                return ResourceManager.GetString("MSBuildExtensionPack_BuildEventCode_Common_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Search"".
        /// </summary>
        public static string MSBuildExtensionPack_BuildEventCode_Common_ShortTitle {
            get {
                return ResourceManager.GetString("MSBuildExtensionPack_BuildEventCode_Common_ShortTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Summary of BuildEventCode:MSBuildExtensionPack_BuildEventCode_Common"".
        /// </summary>
        public static string MSBuildExtensionPack_BuildEventCode_Common_Summary {
            get {
                return ResourceManager.GetString("MSBuildExtensionPack_BuildEventCode_Common_Summary", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Full Details"".
        /// </summary>
        public static string MSBuildExtensionPack_BuildEventCode_FullDetails_Title {
            get {
                return ResourceManager.GetString("MSBuildExtensionPack_BuildEventCode_FullDetails_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Full"".
        /// </summary>
        public static string MSBuildExtensionPack_BuildEventCode_FullDetails_ShortTitle {
            get {
                return ResourceManager.GetString("MSBuildExtensionPack_BuildEventCode_FullDetails_ShortTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Summary of BuildEventCode:MSBuildExtensionPack_BuildEventCode_FullDetails"".
        /// </summary>
        public static string MSBuildExtensionPack_BuildEventCode_FullDetails_Summary {
            get {
                return ResourceManager.GetString("MSBuildExtensionPack_BuildEventCode_FullDetails_Summary", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Common Search View"".
        /// </summary>
        public static string MSBuildExtensionPack_BuildEventCode_CommonSearchView_Title {
            get {
                return ResourceManager.GetString("MSBuildExtensionPack_BuildEventCode_CommonSearchView_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Common"".
        /// </summary>
        public static string MSBuildExtensionPack_BuildEventCode_CommonSearchView_ShortTitle {
            get {
                return ResourceManager.GetString("MSBuildExtensionPack_BuildEventCode_CommonSearchView_ShortTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Summary of BuildEventCode:MSBuildExtensionPack_BuildEventCode_CommonSearchView"".
        /// </summary>
        public static string MSBuildExtensionPack_BuildEventCode_CommonSearchView_Summary {
            get {
                return ResourceManager.GetString("MSBuildExtensionPack_BuildEventCode_CommonSearchView_Summary", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Common Result View"".
        /// </summary>
        public static string MSBuildExtensionPack_BuildEventCode_CommonResultView_Title {
            get {
                return ResourceManager.GetString("MSBuildExtensionPack_BuildEventCode_CommonResultView_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Common"".
        /// </summary>
        public static string MSBuildExtensionPack_BuildEventCode_CommonResultView_ShortTitle {
            get {
                return ResourceManager.GetString("MSBuildExtensionPack_BuildEventCode_CommonResultView_ShortTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Summary of BuildEventCode:MSBuildExtensionPack_BuildEventCode_CommonResultView"".
        /// </summary>
        public static string MSBuildExtensionPack_BuildEventCode_CommonResultView_Summary {
            get {
                return ResourceManager.GetString("MSBuildExtensionPack_BuildEventCode_CommonResultView_Summary", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Tabbed Common"".
        /// </summary>
        public static string MSBuildExtensionPack_BuildEventCode_TabbedCommon_Title {
            get {
                return ResourceManager.GetString("MSBuildExtensionPack_BuildEventCode_TabbedCommon_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Tabbed"".
        /// </summary>
        public static string MSBuildExtensionPack_BuildEventCode_TabbedCommon_ShortTitle {
            get {
                return ResourceManager.GetString("MSBuildExtensionPack_BuildEventCode_TabbedCommon_ShortTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Summary of BuildEventCode:MSBuildExtensionPack_BuildEventCode_TabbedCommon"".
        /// </summary>
        public static string MSBuildExtensionPack_BuildEventCode_TabbedCommon_Summary {
            get {
                return ResourceManager.GetString("MSBuildExtensionPack_BuildEventCode_TabbedCommon_Summary", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Search BuildLog"".
        /// </summary>
        public static string MSBuildExtensionPack_BuildLog_Common_Title {
            get {
                return ResourceManager.GetString("MSBuildExtensionPack_BuildLog_Common_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Search"".
        /// </summary>
        public static string MSBuildExtensionPack_BuildLog_Common_ShortTitle {
            get {
                return ResourceManager.GetString("MSBuildExtensionPack_BuildLog_Common_ShortTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Summary of BuildLog:MSBuildExtensionPack_BuildLog_Common"".
        /// </summary>
        public static string MSBuildExtensionPack_BuildLog_Common_Summary {
            get {
                return ResourceManager.GetString("MSBuildExtensionPack_BuildLog_Common_Summary", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Full Details"".
        /// </summary>
        public static string MSBuildExtensionPack_BuildLog_FullDetails_Title {
            get {
                return ResourceManager.GetString("MSBuildExtensionPack_BuildLog_FullDetails_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Full"".
        /// </summary>
        public static string MSBuildExtensionPack_BuildLog_FullDetails_ShortTitle {
            get {
                return ResourceManager.GetString("MSBuildExtensionPack_BuildLog_FullDetails_ShortTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Summary of BuildLog:MSBuildExtensionPack_BuildLog_FullDetails"".
        /// </summary>
        public static string MSBuildExtensionPack_BuildLog_FullDetails_Summary {
            get {
                return ResourceManager.GetString("MSBuildExtensionPack_BuildLog_FullDetails_Summary", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Common Search View"".
        /// </summary>
        public static string MSBuildExtensionPack_BuildLog_CommonSearchView_Title {
            get {
                return ResourceManager.GetString("MSBuildExtensionPack_BuildLog_CommonSearchView_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Common"".
        /// </summary>
        public static string MSBuildExtensionPack_BuildLog_CommonSearchView_ShortTitle {
            get {
                return ResourceManager.GetString("MSBuildExtensionPack_BuildLog_CommonSearchView_ShortTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Summary of BuildLog:MSBuildExtensionPack_BuildLog_CommonSearchView"".
        /// </summary>
        public static string MSBuildExtensionPack_BuildLog_CommonSearchView_Summary {
            get {
                return ResourceManager.GetString("MSBuildExtensionPack_BuildLog_CommonSearchView_Summary", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Common Result View"".
        /// </summary>
        public static string MSBuildExtensionPack_BuildLog_CommonResultView_Title {
            get {
                return ResourceManager.GetString("MSBuildExtensionPack_BuildLog_CommonResultView_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Common"".
        /// </summary>
        public static string MSBuildExtensionPack_BuildLog_CommonResultView_ShortTitle {
            get {
                return ResourceManager.GetString("MSBuildExtensionPack_BuildLog_CommonResultView_ShortTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Summary of BuildLog:MSBuildExtensionPack_BuildLog_CommonResultView"".
        /// </summary>
        public static string MSBuildExtensionPack_BuildLog_CommonResultView_Summary {
            get {
                return ResourceManager.GetString("MSBuildExtensionPack_BuildLog_CommonResultView_Summary", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Tabbed Common"".
        /// </summary>
        public static string MSBuildExtensionPack_BuildLog_TabbedCommon_Title {
            get {
                return ResourceManager.GetString("MSBuildExtensionPack_BuildLog_TabbedCommon_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Tabbed"".
        /// </summary>
        public static string MSBuildExtensionPack_BuildLog_TabbedCommon_ShortTitle {
            get {
                return ResourceManager.GetString("MSBuildExtensionPack_BuildLog_TabbedCommon_ShortTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Summary of BuildLog:MSBuildExtensionPack_BuildLog_TabbedCommon"".
        /// </summary>
        public static string MSBuildExtensionPack_BuildLog_TabbedCommon_Summary {
            get {
                return ResourceManager.GetString("MSBuildExtensionPack_BuildLog_TabbedCommon_Summary", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Search Organization"".
        /// </summary>
        public static string MSBuildExtensionPack_Organization_Common_Title {
            get {
                return ResourceManager.GetString("MSBuildExtensionPack_Organization_Common_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Search"".
        /// </summary>
        public static string MSBuildExtensionPack_Organization_Common_ShortTitle {
            get {
                return ResourceManager.GetString("MSBuildExtensionPack_Organization_Common_ShortTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Summary of Organization:MSBuildExtensionPack_Organization_Common"".
        /// </summary>
        public static string MSBuildExtensionPack_Organization_Common_Summary {
            get {
                return ResourceManager.GetString("MSBuildExtensionPack_Organization_Common_Summary", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Full Details"".
        /// </summary>
        public static string MSBuildExtensionPack_Organization_FullDetails_Title {
            get {
                return ResourceManager.GetString("MSBuildExtensionPack_Organization_FullDetails_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Full"".
        /// </summary>
        public static string MSBuildExtensionPack_Organization_FullDetails_ShortTitle {
            get {
                return ResourceManager.GetString("MSBuildExtensionPack_Organization_FullDetails_ShortTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Summary of Organization:MSBuildExtensionPack_Organization_FullDetails"".
        /// </summary>
        public static string MSBuildExtensionPack_Organization_FullDetails_Summary {
            get {
                return ResourceManager.GetString("MSBuildExtensionPack_Organization_FullDetails_Summary", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Common Search View"".
        /// </summary>
        public static string MSBuildExtensionPack_Organization_CommonSearchView_Title {
            get {
                return ResourceManager.GetString("MSBuildExtensionPack_Organization_CommonSearchView_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Common"".
        /// </summary>
        public static string MSBuildExtensionPack_Organization_CommonSearchView_ShortTitle {
            get {
                return ResourceManager.GetString("MSBuildExtensionPack_Organization_CommonSearchView_ShortTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Summary of Organization:MSBuildExtensionPack_Organization_CommonSearchView"".
        /// </summary>
        public static string MSBuildExtensionPack_Organization_CommonSearchView_Summary {
            get {
                return ResourceManager.GetString("MSBuildExtensionPack_Organization_CommonSearchView_Summary", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Common Result View"".
        /// </summary>
        public static string MSBuildExtensionPack_Organization_CommonResultView_Title {
            get {
                return ResourceManager.GetString("MSBuildExtensionPack_Organization_CommonResultView_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Common"".
        /// </summary>
        public static string MSBuildExtensionPack_Organization_CommonResultView_ShortTitle {
            get {
                return ResourceManager.GetString("MSBuildExtensionPack_Organization_CommonResultView_ShortTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Summary of Organization:MSBuildExtensionPack_Organization_CommonResultView"".
        /// </summary>
        public static string MSBuildExtensionPack_Organization_CommonResultView_Summary {
            get {
                return ResourceManager.GetString("MSBuildExtensionPack_Organization_CommonResultView_Summary", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Tabbed Common"".
        /// </summary>
        public static string MSBuildExtensionPack_Organization_TabbedCommon_Title {
            get {
                return ResourceManager.GetString("MSBuildExtensionPack_Organization_TabbedCommon_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Tabbed"".
        /// </summary>
        public static string MSBuildExtensionPack_Organization_TabbedCommon_ShortTitle {
            get {
                return ResourceManager.GetString("MSBuildExtensionPack_Organization_TabbedCommon_ShortTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Summary of Organization:MSBuildExtensionPack_Organization_TabbedCommon"".
        /// </summary>
        public static string MSBuildExtensionPack_Organization_TabbedCommon_Summary {
            get {
                return ResourceManager.GetString("MSBuildExtensionPack_Organization_TabbedCommon_Summary", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Search Solution"".
        /// </summary>
        public static string MSBuildExtensionPack_Solution_Common_Title {
            get {
                return ResourceManager.GetString("MSBuildExtensionPack_Solution_Common_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Search"".
        /// </summary>
        public static string MSBuildExtensionPack_Solution_Common_ShortTitle {
            get {
                return ResourceManager.GetString("MSBuildExtensionPack_Solution_Common_ShortTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Summary of Solution:MSBuildExtensionPack_Solution_Common"".
        /// </summary>
        public static string MSBuildExtensionPack_Solution_Common_Summary {
            get {
                return ResourceManager.GetString("MSBuildExtensionPack_Solution_Common_Summary", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Full Details"".
        /// </summary>
        public static string MSBuildExtensionPack_Solution_FullDetails_Title {
            get {
                return ResourceManager.GetString("MSBuildExtensionPack_Solution_FullDetails_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Full"".
        /// </summary>
        public static string MSBuildExtensionPack_Solution_FullDetails_ShortTitle {
            get {
                return ResourceManager.GetString("MSBuildExtensionPack_Solution_FullDetails_ShortTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Summary of Solution:MSBuildExtensionPack_Solution_FullDetails"".
        /// </summary>
        public static string MSBuildExtensionPack_Solution_FullDetails_Summary {
            get {
                return ResourceManager.GetString("MSBuildExtensionPack_Solution_FullDetails_Summary", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Common Search View"".
        /// </summary>
        public static string MSBuildExtensionPack_Solution_CommonSearchView_Title {
            get {
                return ResourceManager.GetString("MSBuildExtensionPack_Solution_CommonSearchView_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Common"".
        /// </summary>
        public static string MSBuildExtensionPack_Solution_CommonSearchView_ShortTitle {
            get {
                return ResourceManager.GetString("MSBuildExtensionPack_Solution_CommonSearchView_ShortTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Summary of Solution:MSBuildExtensionPack_Solution_CommonSearchView"".
        /// </summary>
        public static string MSBuildExtensionPack_Solution_CommonSearchView_Summary {
            get {
                return ResourceManager.GetString("MSBuildExtensionPack_Solution_CommonSearchView_Summary", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Common Result View"".
        /// </summary>
        public static string MSBuildExtensionPack_Solution_CommonResultView_Title {
            get {
                return ResourceManager.GetString("MSBuildExtensionPack_Solution_CommonResultView_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Common"".
        /// </summary>
        public static string MSBuildExtensionPack_Solution_CommonResultView_ShortTitle {
            get {
                return ResourceManager.GetString("MSBuildExtensionPack_Solution_CommonResultView_ShortTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Summary of Solution:MSBuildExtensionPack_Solution_CommonResultView"".
        /// </summary>
        public static string MSBuildExtensionPack_Solution_CommonResultView_Summary {
            get {
                return ResourceManager.GetString("MSBuildExtensionPack_Solution_CommonResultView_Summary", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Tabbed Common"".
        /// </summary>
        public static string MSBuildExtensionPack_Solution_TabbedCommon_Title {
            get {
                return ResourceManager.GetString("MSBuildExtensionPack_Solution_TabbedCommon_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Tabbed"".
        /// </summary>
        public static string MSBuildExtensionPack_Solution_TabbedCommon_ShortTitle {
            get {
                return ResourceManager.GetString("MSBuildExtensionPack_Solution_TabbedCommon_ShortTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Summary of Solution:MSBuildExtensionPack_Solution_TabbedCommon"".
        /// </summary>
        public static string MSBuildExtensionPack_Solution_TabbedCommon_Summary {
            get {
                return ResourceManager.GetString("MSBuildExtensionPack_Solution_TabbedCommon_Summary", resourceCulture);
            }
        }

    }
}

