//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSBuildExtensionPack.Resx {
    using System;
    using System.Reflection;

    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UIStringResourcePerApp {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public UIStringResourcePerApp() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MSBuildExtensionPack.Resx.UIStringResourcePerApp", typeof(UIStringResourcePerApp).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "MSBuildExtensionPack"".
        /// </summary>
        public static string Application_Title {
            get {
                return ResourceManager.GetString("Application_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Description Of Common of MSBuildExtensionPack.Build"".
        /// </summary>
        public static string Description_Of_Common_of_MSBuildExtensionPack_Build {
            get {
                return ResourceManager.GetString("Description_Of_Common_of_MSBuildExtensionPack_Build", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Common of MSBuildExtensionPack.Build"".
        /// </summary>
        public static string Common_of_MSBuildExtensionPack_Build {
            get {
                return ResourceManager.GetString("Common_of_MSBuildExtensionPack_Build", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "ToolTip Of Common of MSBuildExtensionPack.Build"".
        /// </summary>
        public static string ToolTip_Of_Common_of_MSBuildExtensionPack_Build {
            get {
                return ResourceManager.GetString("ToolTip_Of_Common_of_MSBuildExtensionPack_Build", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Description Of EntityRelated of MSBuildExtensionPack.Build"".
        /// </summary>
        public static string Description_Of_EntityRelated_of_MSBuildExtensionPack_Build {
            get {
                return ResourceManager.GetString("Description_Of_EntityRelated_of_MSBuildExtensionPack_Build", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "EntityRelated of MSBuildExtensionPack.Build"".
        /// </summary>
        public static string EntityRelated_of_MSBuildExtensionPack_Build {
            get {
                return ResourceManager.GetString("EntityRelated_of_MSBuildExtensionPack_Build", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "ToolTip Of EntityRelated of MSBuildExtensionPack.Build"".
        /// </summary>
        public static string ToolTip_Of_EntityRelated_of_MSBuildExtensionPack_Build {
            get {
                return ResourceManager.GetString("ToolTip_Of_EntityRelated_of_MSBuildExtensionPack_Build", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Description Of CommonSearchView of MSBuildExtensionPack.Build"".
        /// </summary>
        public static string Description_Of_CommonSearchView_of_MSBuildExtensionPack_Build {
            get {
                return ResourceManager.GetString("Description_Of_CommonSearchView_of_MSBuildExtensionPack_Build", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "CommonSearchView of MSBuildExtensionPack.Build"".
        /// </summary>
        public static string CommonSearchView_of_MSBuildExtensionPack_Build {
            get {
                return ResourceManager.GetString("CommonSearchView_of_MSBuildExtensionPack_Build", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "ToolTip Of CommonSearchView of MSBuildExtensionPack.Build"".
        /// </summary>
        public static string ToolTip_Of_CommonSearchView_of_MSBuildExtensionPack_Build {
            get {
                return ResourceManager.GetString("ToolTip_Of_CommonSearchView_of_MSBuildExtensionPack_Build", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Description Of CommonResultView of MSBuildExtensionPack.Build"".
        /// </summary>
        public static string Description_Of_CommonResultView_of_MSBuildExtensionPack_Build {
            get {
                return ResourceManager.GetString("Description_Of_CommonResultView_of_MSBuildExtensionPack_Build", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "CommonResultView of MSBuildExtensionPack.Build"".
        /// </summary>
        public static string CommonResultView_of_MSBuildExtensionPack_Build {
            get {
                return ResourceManager.GetString("CommonResultView_of_MSBuildExtensionPack_Build", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "ToolTip Of CommonResultView of MSBuildExtensionPack.Build"".
        /// </summary>
        public static string ToolTip_Of_CommonResultView_of_MSBuildExtensionPack_Build {
            get {
                return ResourceManager.GetString("ToolTip_Of_CommonResultView_of_MSBuildExtensionPack_Build", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Description Of TabbedCommon of MSBuildExtensionPack.Build"".
        /// </summary>
        public static string Description_Of_TabbedCommon_of_MSBuildExtensionPack_Build {
            get {
                return ResourceManager.GetString("Description_Of_TabbedCommon_of_MSBuildExtensionPack_Build", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "TabbedCommon of MSBuildExtensionPack.Build"".
        /// </summary>
        public static string TabbedCommon_of_MSBuildExtensionPack_Build {
            get {
                return ResourceManager.GetString("TabbedCommon_of_MSBuildExtensionPack_Build", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "ToolTip Of TabbedCommon of MSBuildExtensionPack.Build"".
        /// </summary>
        public static string ToolTip_Of_TabbedCommon_of_MSBuildExtensionPack_Build {
            get {
                return ResourceManager.GetString("ToolTip_Of_TabbedCommon_of_MSBuildExtensionPack_Build", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Description Of UpdateNameOnly of MSBuildExtensionPack.Build"".
        /// </summary>
        public static string Description_Of_UpdateNameOnly_of_MSBuildExtensionPack_Build {
            get {
                return ResourceManager.GetString("Description_Of_UpdateNameOnly_of_MSBuildExtensionPack_Build", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "UpdateNameOnly of MSBuildExtensionPack.Build"".
        /// </summary>
        public static string UpdateNameOnly_of_MSBuildExtensionPack_Build {
            get {
                return ResourceManager.GetString("UpdateNameOnly_of_MSBuildExtensionPack_Build", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "ToolTip Of UpdateNameOnly of MSBuildExtensionPack.Build"".
        /// </summary>
        public static string ToolTip_Of_UpdateNameOnly_of_MSBuildExtensionPack_Build {
            get {
                return ResourceManager.GetString("ToolTip_Of_UpdateNameOnly_of_MSBuildExtensionPack_Build", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Description Of Common of MSBuildExtensionPack.BuildEventCode"".
        /// </summary>
        public static string Description_Of_Common_of_MSBuildExtensionPack_BuildEventCode {
            get {
                return ResourceManager.GetString("Description_Of_Common_of_MSBuildExtensionPack_BuildEventCode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Common of MSBuildExtensionPack.BuildEventCode"".
        /// </summary>
        public static string Common_of_MSBuildExtensionPack_BuildEventCode {
            get {
                return ResourceManager.GetString("Common_of_MSBuildExtensionPack_BuildEventCode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "ToolTip Of Common of MSBuildExtensionPack.BuildEventCode"".
        /// </summary>
        public static string ToolTip_Of_Common_of_MSBuildExtensionPack_BuildEventCode {
            get {
                return ResourceManager.GetString("ToolTip_Of_Common_of_MSBuildExtensionPack_BuildEventCode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Description Of EntityRelated of MSBuildExtensionPack.BuildEventCode"".
        /// </summary>
        public static string Description_Of_EntityRelated_of_MSBuildExtensionPack_BuildEventCode {
            get {
                return ResourceManager.GetString("Description_Of_EntityRelated_of_MSBuildExtensionPack_BuildEventCode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "EntityRelated of MSBuildExtensionPack.BuildEventCode"".
        /// </summary>
        public static string EntityRelated_of_MSBuildExtensionPack_BuildEventCode {
            get {
                return ResourceManager.GetString("EntityRelated_of_MSBuildExtensionPack_BuildEventCode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "ToolTip Of EntityRelated of MSBuildExtensionPack.BuildEventCode"".
        /// </summary>
        public static string ToolTip_Of_EntityRelated_of_MSBuildExtensionPack_BuildEventCode {
            get {
                return ResourceManager.GetString("ToolTip_Of_EntityRelated_of_MSBuildExtensionPack_BuildEventCode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Description Of CommonSearchView of MSBuildExtensionPack.BuildEventCode"".
        /// </summary>
        public static string Description_Of_CommonSearchView_of_MSBuildExtensionPack_BuildEventCode {
            get {
                return ResourceManager.GetString("Description_Of_CommonSearchView_of_MSBuildExtensionPack_BuildEventCode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "CommonSearchView of MSBuildExtensionPack.BuildEventCode"".
        /// </summary>
        public static string CommonSearchView_of_MSBuildExtensionPack_BuildEventCode {
            get {
                return ResourceManager.GetString("CommonSearchView_of_MSBuildExtensionPack_BuildEventCode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "ToolTip Of CommonSearchView of MSBuildExtensionPack.BuildEventCode"".
        /// </summary>
        public static string ToolTip_Of_CommonSearchView_of_MSBuildExtensionPack_BuildEventCode {
            get {
                return ResourceManager.GetString("ToolTip_Of_CommonSearchView_of_MSBuildExtensionPack_BuildEventCode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Description Of CommonResultView of MSBuildExtensionPack.BuildEventCode"".
        /// </summary>
        public static string Description_Of_CommonResultView_of_MSBuildExtensionPack_BuildEventCode {
            get {
                return ResourceManager.GetString("Description_Of_CommonResultView_of_MSBuildExtensionPack_BuildEventCode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "CommonResultView of MSBuildExtensionPack.BuildEventCode"".
        /// </summary>
        public static string CommonResultView_of_MSBuildExtensionPack_BuildEventCode {
            get {
                return ResourceManager.GetString("CommonResultView_of_MSBuildExtensionPack_BuildEventCode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "ToolTip Of CommonResultView of MSBuildExtensionPack.BuildEventCode"".
        /// </summary>
        public static string ToolTip_Of_CommonResultView_of_MSBuildExtensionPack_BuildEventCode {
            get {
                return ResourceManager.GetString("ToolTip_Of_CommonResultView_of_MSBuildExtensionPack_BuildEventCode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Description Of TabbedCommon of MSBuildExtensionPack.BuildEventCode"".
        /// </summary>
        public static string Description_Of_TabbedCommon_of_MSBuildExtensionPack_BuildEventCode {
            get {
                return ResourceManager.GetString("Description_Of_TabbedCommon_of_MSBuildExtensionPack_BuildEventCode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "TabbedCommon of MSBuildExtensionPack.BuildEventCode"".
        /// </summary>
        public static string TabbedCommon_of_MSBuildExtensionPack_BuildEventCode {
            get {
                return ResourceManager.GetString("TabbedCommon_of_MSBuildExtensionPack_BuildEventCode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "ToolTip Of TabbedCommon of MSBuildExtensionPack.BuildEventCode"".
        /// </summary>
        public static string ToolTip_Of_TabbedCommon_of_MSBuildExtensionPack_BuildEventCode {
            get {
                return ResourceManager.GetString("ToolTip_Of_TabbedCommon_of_MSBuildExtensionPack_BuildEventCode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Description Of Common of MSBuildExtensionPack.BuildLog"".
        /// </summary>
        public static string Description_Of_Common_of_MSBuildExtensionPack_BuildLog {
            get {
                return ResourceManager.GetString("Description_Of_Common_of_MSBuildExtensionPack_BuildLog", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Common of MSBuildExtensionPack.BuildLog"".
        /// </summary>
        public static string Common_of_MSBuildExtensionPack_BuildLog {
            get {
                return ResourceManager.GetString("Common_of_MSBuildExtensionPack_BuildLog", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "ToolTip Of Common of MSBuildExtensionPack.BuildLog"".
        /// </summary>
        public static string ToolTip_Of_Common_of_MSBuildExtensionPack_BuildLog {
            get {
                return ResourceManager.GetString("ToolTip_Of_Common_of_MSBuildExtensionPack_BuildLog", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Description Of EntityRelated of MSBuildExtensionPack.BuildLog"".
        /// </summary>
        public static string Description_Of_EntityRelated_of_MSBuildExtensionPack_BuildLog {
            get {
                return ResourceManager.GetString("Description_Of_EntityRelated_of_MSBuildExtensionPack_BuildLog", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "EntityRelated of MSBuildExtensionPack.BuildLog"".
        /// </summary>
        public static string EntityRelated_of_MSBuildExtensionPack_BuildLog {
            get {
                return ResourceManager.GetString("EntityRelated_of_MSBuildExtensionPack_BuildLog", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "ToolTip Of EntityRelated of MSBuildExtensionPack.BuildLog"".
        /// </summary>
        public static string ToolTip_Of_EntityRelated_of_MSBuildExtensionPack_BuildLog {
            get {
                return ResourceManager.GetString("ToolTip_Of_EntityRelated_of_MSBuildExtensionPack_BuildLog", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Description Of CommonSearchView of MSBuildExtensionPack.BuildLog"".
        /// </summary>
        public static string Description_Of_CommonSearchView_of_MSBuildExtensionPack_BuildLog {
            get {
                return ResourceManager.GetString("Description_Of_CommonSearchView_of_MSBuildExtensionPack_BuildLog", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "CommonSearchView of MSBuildExtensionPack.BuildLog"".
        /// </summary>
        public static string CommonSearchView_of_MSBuildExtensionPack_BuildLog {
            get {
                return ResourceManager.GetString("CommonSearchView_of_MSBuildExtensionPack_BuildLog", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "ToolTip Of CommonSearchView of MSBuildExtensionPack.BuildLog"".
        /// </summary>
        public static string ToolTip_Of_CommonSearchView_of_MSBuildExtensionPack_BuildLog {
            get {
                return ResourceManager.GetString("ToolTip_Of_CommonSearchView_of_MSBuildExtensionPack_BuildLog", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Description Of CommonResultView of MSBuildExtensionPack.BuildLog"".
        /// </summary>
        public static string Description_Of_CommonResultView_of_MSBuildExtensionPack_BuildLog {
            get {
                return ResourceManager.GetString("Description_Of_CommonResultView_of_MSBuildExtensionPack_BuildLog", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "CommonResultView of MSBuildExtensionPack.BuildLog"".
        /// </summary>
        public static string CommonResultView_of_MSBuildExtensionPack_BuildLog {
            get {
                return ResourceManager.GetString("CommonResultView_of_MSBuildExtensionPack_BuildLog", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "ToolTip Of CommonResultView of MSBuildExtensionPack.BuildLog"".
        /// </summary>
        public static string ToolTip_Of_CommonResultView_of_MSBuildExtensionPack_BuildLog {
            get {
                return ResourceManager.GetString("ToolTip_Of_CommonResultView_of_MSBuildExtensionPack_BuildLog", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Description Of TabbedCommon of MSBuildExtensionPack.BuildLog"".
        /// </summary>
        public static string Description_Of_TabbedCommon_of_MSBuildExtensionPack_BuildLog {
            get {
                return ResourceManager.GetString("Description_Of_TabbedCommon_of_MSBuildExtensionPack_BuildLog", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "TabbedCommon of MSBuildExtensionPack.BuildLog"".
        /// </summary>
        public static string TabbedCommon_of_MSBuildExtensionPack_BuildLog {
            get {
                return ResourceManager.GetString("TabbedCommon_of_MSBuildExtensionPack_BuildLog", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "ToolTip Of TabbedCommon of MSBuildExtensionPack.BuildLog"".
        /// </summary>
        public static string ToolTip_Of_TabbedCommon_of_MSBuildExtensionPack_BuildLog {
            get {
                return ResourceManager.GetString("ToolTip_Of_TabbedCommon_of_MSBuildExtensionPack_BuildLog", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Description Of Common of MSBuildExtensionPack.Organization"".
        /// </summary>
        public static string Description_Of_Common_of_MSBuildExtensionPack_Organization {
            get {
                return ResourceManager.GetString("Description_Of_Common_of_MSBuildExtensionPack_Organization", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Common of MSBuildExtensionPack.Organization"".
        /// </summary>
        public static string Common_of_MSBuildExtensionPack_Organization {
            get {
                return ResourceManager.GetString("Common_of_MSBuildExtensionPack_Organization", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "ToolTip Of Common of MSBuildExtensionPack.Organization"".
        /// </summary>
        public static string ToolTip_Of_Common_of_MSBuildExtensionPack_Organization {
            get {
                return ResourceManager.GetString("ToolTip_Of_Common_of_MSBuildExtensionPack_Organization", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Description Of EntityRelated of MSBuildExtensionPack.Organization"".
        /// </summary>
        public static string Description_Of_EntityRelated_of_MSBuildExtensionPack_Organization {
            get {
                return ResourceManager.GetString("Description_Of_EntityRelated_of_MSBuildExtensionPack_Organization", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "EntityRelated of MSBuildExtensionPack.Organization"".
        /// </summary>
        public static string EntityRelated_of_MSBuildExtensionPack_Organization {
            get {
                return ResourceManager.GetString("EntityRelated_of_MSBuildExtensionPack_Organization", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "ToolTip Of EntityRelated of MSBuildExtensionPack.Organization"".
        /// </summary>
        public static string ToolTip_Of_EntityRelated_of_MSBuildExtensionPack_Organization {
            get {
                return ResourceManager.GetString("ToolTip_Of_EntityRelated_of_MSBuildExtensionPack_Organization", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Description Of CommonSearchView of MSBuildExtensionPack.Organization"".
        /// </summary>
        public static string Description_Of_CommonSearchView_of_MSBuildExtensionPack_Organization {
            get {
                return ResourceManager.GetString("Description_Of_CommonSearchView_of_MSBuildExtensionPack_Organization", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "CommonSearchView of MSBuildExtensionPack.Organization"".
        /// </summary>
        public static string CommonSearchView_of_MSBuildExtensionPack_Organization {
            get {
                return ResourceManager.GetString("CommonSearchView_of_MSBuildExtensionPack_Organization", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "ToolTip Of CommonSearchView of MSBuildExtensionPack.Organization"".
        /// </summary>
        public static string ToolTip_Of_CommonSearchView_of_MSBuildExtensionPack_Organization {
            get {
                return ResourceManager.GetString("ToolTip_Of_CommonSearchView_of_MSBuildExtensionPack_Organization", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Description Of CommonResultView of MSBuildExtensionPack.Organization"".
        /// </summary>
        public static string Description_Of_CommonResultView_of_MSBuildExtensionPack_Organization {
            get {
                return ResourceManager.GetString("Description_Of_CommonResultView_of_MSBuildExtensionPack_Organization", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "CommonResultView of MSBuildExtensionPack.Organization"".
        /// </summary>
        public static string CommonResultView_of_MSBuildExtensionPack_Organization {
            get {
                return ResourceManager.GetString("CommonResultView_of_MSBuildExtensionPack_Organization", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "ToolTip Of CommonResultView of MSBuildExtensionPack.Organization"".
        /// </summary>
        public static string ToolTip_Of_CommonResultView_of_MSBuildExtensionPack_Organization {
            get {
                return ResourceManager.GetString("ToolTip_Of_CommonResultView_of_MSBuildExtensionPack_Organization", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Description Of TabbedCommon of MSBuildExtensionPack.Organization"".
        /// </summary>
        public static string Description_Of_TabbedCommon_of_MSBuildExtensionPack_Organization {
            get {
                return ResourceManager.GetString("Description_Of_TabbedCommon_of_MSBuildExtensionPack_Organization", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "TabbedCommon of MSBuildExtensionPack.Organization"".
        /// </summary>
        public static string TabbedCommon_of_MSBuildExtensionPack_Organization {
            get {
                return ResourceManager.GetString("TabbedCommon_of_MSBuildExtensionPack_Organization", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "ToolTip Of TabbedCommon of MSBuildExtensionPack.Organization"".
        /// </summary>
        public static string ToolTip_Of_TabbedCommon_of_MSBuildExtensionPack_Organization {
            get {
                return ResourceManager.GetString("ToolTip_Of_TabbedCommon_of_MSBuildExtensionPack_Organization", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Description Of Common of MSBuildExtensionPack.Solution"".
        /// </summary>
        public static string Description_Of_Common_of_MSBuildExtensionPack_Solution {
            get {
                return ResourceManager.GetString("Description_Of_Common_of_MSBuildExtensionPack_Solution", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Common of MSBuildExtensionPack.Solution"".
        /// </summary>
        public static string Common_of_MSBuildExtensionPack_Solution {
            get {
                return ResourceManager.GetString("Common_of_MSBuildExtensionPack_Solution", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "ToolTip Of Common of MSBuildExtensionPack.Solution"".
        /// </summary>
        public static string ToolTip_Of_Common_of_MSBuildExtensionPack_Solution {
            get {
                return ResourceManager.GetString("ToolTip_Of_Common_of_MSBuildExtensionPack_Solution", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Description Of EntityRelated of MSBuildExtensionPack.Solution"".
        /// </summary>
        public static string Description_Of_EntityRelated_of_MSBuildExtensionPack_Solution {
            get {
                return ResourceManager.GetString("Description_Of_EntityRelated_of_MSBuildExtensionPack_Solution", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "EntityRelated of MSBuildExtensionPack.Solution"".
        /// </summary>
        public static string EntityRelated_of_MSBuildExtensionPack_Solution {
            get {
                return ResourceManager.GetString("EntityRelated_of_MSBuildExtensionPack_Solution", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "ToolTip Of EntityRelated of MSBuildExtensionPack.Solution"".
        /// </summary>
        public static string ToolTip_Of_EntityRelated_of_MSBuildExtensionPack_Solution {
            get {
                return ResourceManager.GetString("ToolTip_Of_EntityRelated_of_MSBuildExtensionPack_Solution", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Description Of CommonSearchView of MSBuildExtensionPack.Solution"".
        /// </summary>
        public static string Description_Of_CommonSearchView_of_MSBuildExtensionPack_Solution {
            get {
                return ResourceManager.GetString("Description_Of_CommonSearchView_of_MSBuildExtensionPack_Solution", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "CommonSearchView of MSBuildExtensionPack.Solution"".
        /// </summary>
        public static string CommonSearchView_of_MSBuildExtensionPack_Solution {
            get {
                return ResourceManager.GetString("CommonSearchView_of_MSBuildExtensionPack_Solution", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "ToolTip Of CommonSearchView of MSBuildExtensionPack.Solution"".
        /// </summary>
        public static string ToolTip_Of_CommonSearchView_of_MSBuildExtensionPack_Solution {
            get {
                return ResourceManager.GetString("ToolTip_Of_CommonSearchView_of_MSBuildExtensionPack_Solution", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Description Of CommonResultView of MSBuildExtensionPack.Solution"".
        /// </summary>
        public static string Description_Of_CommonResultView_of_MSBuildExtensionPack_Solution {
            get {
                return ResourceManager.GetString("Description_Of_CommonResultView_of_MSBuildExtensionPack_Solution", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "CommonResultView of MSBuildExtensionPack.Solution"".
        /// </summary>
        public static string CommonResultView_of_MSBuildExtensionPack_Solution {
            get {
                return ResourceManager.GetString("CommonResultView_of_MSBuildExtensionPack_Solution", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "ToolTip Of CommonResultView of MSBuildExtensionPack.Solution"".
        /// </summary>
        public static string ToolTip_Of_CommonResultView_of_MSBuildExtensionPack_Solution {
            get {
                return ResourceManager.GetString("ToolTip_Of_CommonResultView_of_MSBuildExtensionPack_Solution", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Description Of TabbedCommon of MSBuildExtensionPack.Solution"".
        /// </summary>
        public static string Description_Of_TabbedCommon_of_MSBuildExtensionPack_Solution {
            get {
                return ResourceManager.GetString("Description_Of_TabbedCommon_of_MSBuildExtensionPack_Solution", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "TabbedCommon of MSBuildExtensionPack.Solution"".
        /// </summary>
        public static string TabbedCommon_of_MSBuildExtensionPack_Solution {
            get {
                return ResourceManager.GetString("TabbedCommon_of_MSBuildExtensionPack_Solution", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "ToolTip Of TabbedCommon of MSBuildExtensionPack.Solution"".
        /// </summary>
        public static string ToolTip_Of_TabbedCommon_of_MSBuildExtensionPack_Solution {
            get {
                return ResourceManager.GetString("ToolTip_Of_TabbedCommon_of_MSBuildExtensionPack_Solution", resourceCulture);
            }
        }

    }
}

