//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSBuildExtensionPack.Resx {
    using System;
    using System.Reflection;

    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UIStringResourcePerApp {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public UIStringResourcePerApp() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MSBuildExtensionPack.Resx.UIStringResourcePerApp", typeof(UIStringResourcePerApp).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "MSBuildExtensionPack"".
        /// </summary>
        public static string Application_Title {
            get {
                return ResourceManager.GetString("Application_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Description Of MSBuildExtensionPack_Build_Common"".
        /// </summary>
        public static string Description_Of_MSBuildExtensionPack_Build_Common {
            get {
                return ResourceManager.GetString("Description_Of_MSBuildExtensionPack_Build_Common", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "MSBuildExtensionPack_Build_Common"".
        /// </summary>
        public static string MSBuildExtensionPack_Build_Common {
            get {
                return ResourceManager.GetString("MSBuildExtensionPack_Build_Common", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "ToolTip Of MSBuildExtensionPack_Build_Common"".
        /// </summary>
        public static string ToolTip_Of_MSBuildExtensionPack_Build_Common {
            get {
                return ResourceManager.GetString("ToolTip_Of_MSBuildExtensionPack_Build_Common", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Description Of MSBuildExtensionPack_Build_FullDetails"".
        /// </summary>
        public static string Description_Of_MSBuildExtensionPack_Build_FullDetails {
            get {
                return ResourceManager.GetString("Description_Of_MSBuildExtensionPack_Build_FullDetails", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "MSBuildExtensionPack_Build_FullDetails"".
        /// </summary>
        public static string MSBuildExtensionPack_Build_FullDetails {
            get {
                return ResourceManager.GetString("MSBuildExtensionPack_Build_FullDetails", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "ToolTip Of MSBuildExtensionPack_Build_FullDetails"".
        /// </summary>
        public static string ToolTip_Of_MSBuildExtensionPack_Build_FullDetails {
            get {
                return ResourceManager.GetString("ToolTip_Of_MSBuildExtensionPack_Build_FullDetails", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Description Of MSBuildExtensionPack_Build_CommonSearchView"".
        /// </summary>
        public static string Description_Of_MSBuildExtensionPack_Build_CommonSearchView {
            get {
                return ResourceManager.GetString("Description_Of_MSBuildExtensionPack_Build_CommonSearchView", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "MSBuildExtensionPack_Build_CommonSearchView"".
        /// </summary>
        public static string MSBuildExtensionPack_Build_CommonSearchView {
            get {
                return ResourceManager.GetString("MSBuildExtensionPack_Build_CommonSearchView", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "ToolTip Of MSBuildExtensionPack_Build_CommonSearchView"".
        /// </summary>
        public static string ToolTip_Of_MSBuildExtensionPack_Build_CommonSearchView {
            get {
                return ResourceManager.GetString("ToolTip_Of_MSBuildExtensionPack_Build_CommonSearchView", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Description Of MSBuildExtensionPack_Build_CommonResultView"".
        /// </summary>
        public static string Description_Of_MSBuildExtensionPack_Build_CommonResultView {
            get {
                return ResourceManager.GetString("Description_Of_MSBuildExtensionPack_Build_CommonResultView", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "MSBuildExtensionPack_Build_CommonResultView"".
        /// </summary>
        public static string MSBuildExtensionPack_Build_CommonResultView {
            get {
                return ResourceManager.GetString("MSBuildExtensionPack_Build_CommonResultView", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "ToolTip Of MSBuildExtensionPack_Build_CommonResultView"".
        /// </summary>
        public static string ToolTip_Of_MSBuildExtensionPack_Build_CommonResultView {
            get {
                return ResourceManager.GetString("ToolTip_Of_MSBuildExtensionPack_Build_CommonResultView", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Description Of MSBuildExtensionPack_Build_TabbedCommon"".
        /// </summary>
        public static string Description_Of_MSBuildExtensionPack_Build_TabbedCommon {
            get {
                return ResourceManager.GetString("Description_Of_MSBuildExtensionPack_Build_TabbedCommon", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "MSBuildExtensionPack_Build_TabbedCommon"".
        /// </summary>
        public static string MSBuildExtensionPack_Build_TabbedCommon {
            get {
                return ResourceManager.GetString("MSBuildExtensionPack_Build_TabbedCommon", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "ToolTip Of MSBuildExtensionPack_Build_TabbedCommon"".
        /// </summary>
        public static string ToolTip_Of_MSBuildExtensionPack_Build_TabbedCommon {
            get {
                return ResourceManager.GetString("ToolTip_Of_MSBuildExtensionPack_Build_TabbedCommon", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Description Of MSBuildExtensionPack_Build_something"".
        /// </summary>
        public static string Description_Of_MSBuildExtensionPack_Build_something {
            get {
                return ResourceManager.GetString("Description_Of_MSBuildExtensionPack_Build_something", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "MSBuildExtensionPack_Build_something"".
        /// </summary>
        public static string MSBuildExtensionPack_Build_something {
            get {
                return ResourceManager.GetString("MSBuildExtensionPack_Build_something", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "ToolTip Of MSBuildExtensionPack_Build_something"".
        /// </summary>
        public static string ToolTip_Of_MSBuildExtensionPack_Build_something {
            get {
                return ResourceManager.GetString("ToolTip_Of_MSBuildExtensionPack_Build_something", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Description Of MSBuildExtensionPack_Build_elsesomething"".
        /// </summary>
        public static string Description_Of_MSBuildExtensionPack_Build_elsesomething {
            get {
                return ResourceManager.GetString("Description_Of_MSBuildExtensionPack_Build_elsesomething", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "MSBuildExtensionPack_Build_elsesomething"".
        /// </summary>
        public static string MSBuildExtensionPack_Build_elsesomething {
            get {
                return ResourceManager.GetString("MSBuildExtensionPack_Build_elsesomething", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "ToolTip Of MSBuildExtensionPack_Build_elsesomething"".
        /// </summary>
        public static string ToolTip_Of_MSBuildExtensionPack_Build_elsesomething {
            get {
                return ResourceManager.GetString("ToolTip_Of_MSBuildExtensionPack_Build_elsesomething", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Description Of MSBuildExtensionPack_Build_elseA1Asomething"".
        /// </summary>
        public static string Description_Of_MSBuildExtensionPack_Build_elseA1Asomething {
            get {
                return ResourceManager.GetString("Description_Of_MSBuildExtensionPack_Build_elseA1Asomething", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "MSBuildExtensionPack_Build_elseA1Asomething"".
        /// </summary>
        public static string MSBuildExtensionPack_Build_elseA1Asomething {
            get {
                return ResourceManager.GetString("MSBuildExtensionPack_Build_elseA1Asomething", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "ToolTip Of MSBuildExtensionPack_Build_elseA1Asomething"".
        /// </summary>
        public static string ToolTip_Of_MSBuildExtensionPack_Build_elseA1Asomething {
            get {
                return ResourceManager.GetString("ToolTip_Of_MSBuildExtensionPack_Build_elseA1Asomething", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "MSBuildExtensionPack_Build_elseA1Asomething"".
        /// </summary>
        public static string MSBuildExtensionPack_Build_elseA1Asomething_ButtonText {
            get {
                return ResourceManager.GetString("MSBuildExtensionPack_Build_elseA1Asomething_ButtonText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "MSBuildExtensionPack_Build_elseA1Asomething"".
        /// </summary>
        public static string MSBuildExtensionPack_Build_elseA1Asomething_Description {
            get {
                return ResourceManager.GetString("MSBuildExtensionPack_Build_elseA1Asomething_Description", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "MSBuildExtensionPack_Build_elseA1Asomething success."".
        /// </summary>
        public static string MSBuildExtensionPack_Build_elseA1Asomething_Success {
            get {
                return ResourceManager.GetString("MSBuildExtensionPack_Build_elseA1Asomething_Success", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "MSBuildExtensionPack_Build_elseA1Asomething failed."".
        /// </summary>
        public static string MSBuildExtensionPack_Build_elseA1Asomething_Failed {
            get {
                return ResourceManager.GetString("MSBuildExtensionPack_Build_elseA1Asomething_Failed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Description Of MSBuildExtensionPack_Build_somethingSearch"".
        /// </summary>
        public static string Description_Of_MSBuildExtensionPack_Build_somethingSearch {
            get {
                return ResourceManager.GetString("Description_Of_MSBuildExtensionPack_Build_somethingSearch", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "MSBuildExtensionPack_Build_somethingSearch"".
        /// </summary>
        public static string MSBuildExtensionPack_Build_somethingSearch {
            get {
                return ResourceManager.GetString("MSBuildExtensionPack_Build_somethingSearch", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "ToolTip Of MSBuildExtensionPack_Build_somethingSearch"".
        /// </summary>
        public static string ToolTip_Of_MSBuildExtensionPack_Build_somethingSearch {
            get {
                return ResourceManager.GetString("ToolTip_Of_MSBuildExtensionPack_Build_somethingSearch", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Description Of MSBuildExtensionPack_Build_somethingResult"".
        /// </summary>
        public static string Description_Of_MSBuildExtensionPack_Build_somethingResult {
            get {
                return ResourceManager.GetString("Description_Of_MSBuildExtensionPack_Build_somethingResult", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "MSBuildExtensionPack_Build_somethingResult"".
        /// </summary>
        public static string MSBuildExtensionPack_Build_somethingResult {
            get {
                return ResourceManager.GetString("MSBuildExtensionPack_Build_somethingResult", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "ToolTip Of MSBuildExtensionPack_Build_somethingResult"".
        /// </summary>
        public static string ToolTip_Of_MSBuildExtensionPack_Build_somethingResult {
            get {
                return ResourceManager.GetString("ToolTip_Of_MSBuildExtensionPack_Build_somethingResult", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Description Of MSBuildExtensionPack_Build_somethingTab"".
        /// </summary>
        public static string Description_Of_MSBuildExtensionPack_Build_somethingTab {
            get {
                return ResourceManager.GetString("Description_Of_MSBuildExtensionPack_Build_somethingTab", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "MSBuildExtensionPack_Build_somethingTab"".
        /// </summary>
        public static string MSBuildExtensionPack_Build_somethingTab {
            get {
                return ResourceManager.GetString("MSBuildExtensionPack_Build_somethingTab", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "ToolTip Of MSBuildExtensionPack_Build_somethingTab"".
        /// </summary>
        public static string ToolTip_Of_MSBuildExtensionPack_Build_somethingTab {
            get {
                return ResourceManager.GetString("ToolTip_Of_MSBuildExtensionPack_Build_somethingTab", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Description Of MSBuildExtensionPack_Build_xTabSomethingSearch"".
        /// </summary>
        public static string Description_Of_MSBuildExtensionPack_Build_xTabSomethingSearch {
            get {
                return ResourceManager.GetString("Description_Of_MSBuildExtensionPack_Build_xTabSomethingSearch", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "MSBuildExtensionPack_Build_xTabSomethingSearch"".
        /// </summary>
        public static string MSBuildExtensionPack_Build_xTabSomethingSearch {
            get {
                return ResourceManager.GetString("MSBuildExtensionPack_Build_xTabSomethingSearch", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "ToolTip Of MSBuildExtensionPack_Build_xTabSomethingSearch"".
        /// </summary>
        public static string ToolTip_Of_MSBuildExtensionPack_Build_xTabSomethingSearch {
            get {
                return ResourceManager.GetString("ToolTip_Of_MSBuildExtensionPack_Build_xTabSomethingSearch", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Description Of MSBuildExtensionPack_Build_xTabSomethingResults"".
        /// </summary>
        public static string Description_Of_MSBuildExtensionPack_Build_xTabSomethingResults {
            get {
                return ResourceManager.GetString("Description_Of_MSBuildExtensionPack_Build_xTabSomethingResults", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "MSBuildExtensionPack_Build_xTabSomethingResults"".
        /// </summary>
        public static string MSBuildExtensionPack_Build_xTabSomethingResults {
            get {
                return ResourceManager.GetString("MSBuildExtensionPack_Build_xTabSomethingResults", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "ToolTip Of MSBuildExtensionPack_Build_xTabSomethingResults"".
        /// </summary>
        public static string ToolTip_Of_MSBuildExtensionPack_Build_xTabSomethingResults {
            get {
                return ResourceManager.GetString("ToolTip_Of_MSBuildExtensionPack_Build_xTabSomethingResults", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Description Of MSBuildExtensionPack_Build_xTabSomethingTabContainer"".
        /// </summary>
        public static string Description_Of_MSBuildExtensionPack_Build_xTabSomethingTabContainer {
            get {
                return ResourceManager.GetString("Description_Of_MSBuildExtensionPack_Build_xTabSomethingTabContainer", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "MSBuildExtensionPack_Build_xTabSomethingTabContainer"".
        /// </summary>
        public static string MSBuildExtensionPack_Build_xTabSomethingTabContainer {
            get {
                return ResourceManager.GetString("MSBuildExtensionPack_Build_xTabSomethingTabContainer", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "ToolTip Of MSBuildExtensionPack_Build_xTabSomethingTabContainer"".
        /// </summary>
        public static string ToolTip_Of_MSBuildExtensionPack_Build_xTabSomethingTabContainer {
            get {
                return ResourceManager.GetString("ToolTip_Of_MSBuildExtensionPack_Build_xTabSomethingTabContainer", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Description Of MSBuildExtensionPack_Build_xTabSomething"".
        /// </summary>
        public static string Description_Of_MSBuildExtensionPack_Build_xTabSomething {
            get {
                return ResourceManager.GetString("Description_Of_MSBuildExtensionPack_Build_xTabSomething", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "MSBuildExtensionPack_Build_xTabSomething"".
        /// </summary>
        public static string MSBuildExtensionPack_Build_xTabSomething {
            get {
                return ResourceManager.GetString("MSBuildExtensionPack_Build_xTabSomething", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "ToolTip Of MSBuildExtensionPack_Build_xTabSomething"".
        /// </summary>
        public static string ToolTip_Of_MSBuildExtensionPack_Build_xTabSomething {
            get {
                return ResourceManager.GetString("ToolTip_Of_MSBuildExtensionPack_Build_xTabSomething", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Description Of MSBuildExtensionPack_Build_xTabFullDetailsMasterView"".
        /// </summary>
        public static string Description_Of_MSBuildExtensionPack_Build_xTabFullDetailsMasterView {
            get {
                return ResourceManager.GetString("Description_Of_MSBuildExtensionPack_Build_xTabFullDetailsMasterView", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "MSBuildExtensionPack_Build_xTabFullDetailsMasterView"".
        /// </summary>
        public static string MSBuildExtensionPack_Build_xTabFullDetailsMasterView {
            get {
                return ResourceManager.GetString("MSBuildExtensionPack_Build_xTabFullDetailsMasterView", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "ToolTip Of MSBuildExtensionPack_Build_xTabFullDetailsMasterView"".
        /// </summary>
        public static string ToolTip_Of_MSBuildExtensionPack_Build_xTabFullDetailsMasterView {
            get {
                return ResourceManager.GetString("ToolTip_Of_MSBuildExtensionPack_Build_xTabFullDetailsMasterView", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Description Of MSBuildExtensionPack_Build_xTabFullDetailsAncestorsSolution_1"".
        /// </summary>
        public static string Description_Of_MSBuildExtensionPack_Build_xTabFullDetailsAncestorsSolution_1 {
            get {
                return ResourceManager.GetString("Description_Of_MSBuildExtensionPack_Build_xTabFullDetailsAncestorsSolution_1", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "MSBuildExtensionPack_Build_xTabFullDetailsAncestorsSolution_1"".
        /// </summary>
        public static string MSBuildExtensionPack_Build_xTabFullDetailsAncestorsSolution_1 {
            get {
                return ResourceManager.GetString("MSBuildExtensionPack_Build_xTabFullDetailsAncestorsSolution_1", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "ToolTip Of MSBuildExtensionPack_Build_xTabFullDetailsAncestorsSolution_1"".
        /// </summary>
        public static string ToolTip_Of_MSBuildExtensionPack_Build_xTabFullDetailsAncestorsSolution_1 {
            get {
                return ResourceManager.GetString("ToolTip_Of_MSBuildExtensionPack_Build_xTabFullDetailsAncestorsSolution_1", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Description Of MSBuildExtensionPack_Build_xTabFullDetailsAncestorsOrganization_1"".
        /// </summary>
        public static string Description_Of_MSBuildExtensionPack_Build_xTabFullDetailsAncestorsOrganization_1 {
            get {
                return ResourceManager.GetString("Description_Of_MSBuildExtensionPack_Build_xTabFullDetailsAncestorsOrganization_1", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "MSBuildExtensionPack_Build_xTabFullDetailsAncestorsOrganization_1"".
        /// </summary>
        public static string MSBuildExtensionPack_Build_xTabFullDetailsAncestorsOrganization_1 {
            get {
                return ResourceManager.GetString("MSBuildExtensionPack_Build_xTabFullDetailsAncestorsOrganization_1", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "ToolTip Of MSBuildExtensionPack_Build_xTabFullDetailsAncestorsOrganization_1"".
        /// </summary>
        public static string ToolTip_Of_MSBuildExtensionPack_Build_xTabFullDetailsAncestorsOrganization_1 {
            get {
                return ResourceManager.GetString("ToolTip_Of_MSBuildExtensionPack_Build_xTabFullDetailsAncestorsOrganization_1", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Description Of MSBuildExtensionPack_Build_xTabFullDetailsAncestorsOrganization_2"".
        /// </summary>
        public static string Description_Of_MSBuildExtensionPack_Build_xTabFullDetailsAncestorsOrganization_2 {
            get {
                return ResourceManager.GetString("Description_Of_MSBuildExtensionPack_Build_xTabFullDetailsAncestorsOrganization_2", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "MSBuildExtensionPack_Build_xTabFullDetailsAncestorsOrganization_2"".
        /// </summary>
        public static string MSBuildExtensionPack_Build_xTabFullDetailsAncestorsOrganization_2 {
            get {
                return ResourceManager.GetString("MSBuildExtensionPack_Build_xTabFullDetailsAncestorsOrganization_2", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "ToolTip Of MSBuildExtensionPack_Build_xTabFullDetailsAncestorsOrganization_2"".
        /// </summary>
        public static string ToolTip_Of_MSBuildExtensionPack_Build_xTabFullDetailsAncestorsOrganization_2 {
            get {
                return ResourceManager.GetString("ToolTip_Of_MSBuildExtensionPack_Build_xTabFullDetailsAncestorsOrganization_2", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Description Of MSBuildExtensionPack_Build_xTabFullDetailsFK_BuildLog_Build"".
        /// </summary>
        public static string Description_Of_MSBuildExtensionPack_Build_xTabFullDetailsFK_BuildLog_Build {
            get {
                return ResourceManager.GetString("Description_Of_MSBuildExtensionPack_Build_xTabFullDetailsFK_BuildLog_Build", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "MSBuildExtensionPack_Build_xTabFullDetailsFK_BuildLog_Build"".
        /// </summary>
        public static string MSBuildExtensionPack_Build_xTabFullDetailsFK_BuildLog_Build {
            get {
                return ResourceManager.GetString("MSBuildExtensionPack_Build_xTabFullDetailsFK_BuildLog_Build", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "ToolTip Of MSBuildExtensionPack_Build_xTabFullDetailsFK_BuildLog_Build"".
        /// </summary>
        public static string ToolTip_Of_MSBuildExtensionPack_Build_xTabFullDetailsFK_BuildLog_Build {
            get {
                return ResourceManager.GetString("ToolTip_Of_MSBuildExtensionPack_Build_xTabFullDetailsFK_BuildLog_Build", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Description Of MSBuildExtensionPack_Build_xTabFullDetailsTabContainer"".
        /// </summary>
        public static string Description_Of_MSBuildExtensionPack_Build_xTabFullDetailsTabContainer {
            get {
                return ResourceManager.GetString("Description_Of_MSBuildExtensionPack_Build_xTabFullDetailsTabContainer", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "MSBuildExtensionPack_Build_xTabFullDetailsTabContainer"".
        /// </summary>
        public static string MSBuildExtensionPack_Build_xTabFullDetailsTabContainer {
            get {
                return ResourceManager.GetString("MSBuildExtensionPack_Build_xTabFullDetailsTabContainer", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "ToolTip Of MSBuildExtensionPack_Build_xTabFullDetailsTabContainer"".
        /// </summary>
        public static string ToolTip_Of_MSBuildExtensionPack_Build_xTabFullDetailsTabContainer {
            get {
                return ResourceManager.GetString("ToolTip_Of_MSBuildExtensionPack_Build_xTabFullDetailsTabContainer", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Description Of MSBuildExtensionPack_Build_xTabFullDetails"".
        /// </summary>
        public static string Description_Of_MSBuildExtensionPack_Build_xTabFullDetails {
            get {
                return ResourceManager.GetString("Description_Of_MSBuildExtensionPack_Build_xTabFullDetails", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "MSBuildExtensionPack_Build_xTabFullDetails"".
        /// </summary>
        public static string MSBuildExtensionPack_Build_xTabFullDetails {
            get {
                return ResourceManager.GetString("MSBuildExtensionPack_Build_xTabFullDetails", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "ToolTip Of MSBuildExtensionPack_Build_xTabFullDetails"".
        /// </summary>
        public static string ToolTip_Of_MSBuildExtensionPack_Build_xTabFullDetails {
            get {
                return ResourceManager.GetString("ToolTip_Of_MSBuildExtensionPack_Build_xTabFullDetails", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Description Of MSBuildExtensionPack_BuildEventCode_Common"".
        /// </summary>
        public static string Description_Of_MSBuildExtensionPack_BuildEventCode_Common {
            get {
                return ResourceManager.GetString("Description_Of_MSBuildExtensionPack_BuildEventCode_Common", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "MSBuildExtensionPack_BuildEventCode_Common"".
        /// </summary>
        public static string MSBuildExtensionPack_BuildEventCode_Common {
            get {
                return ResourceManager.GetString("MSBuildExtensionPack_BuildEventCode_Common", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "ToolTip Of MSBuildExtensionPack_BuildEventCode_Common"".
        /// </summary>
        public static string ToolTip_Of_MSBuildExtensionPack_BuildEventCode_Common {
            get {
                return ResourceManager.GetString("ToolTip_Of_MSBuildExtensionPack_BuildEventCode_Common", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Description Of MSBuildExtensionPack_BuildEventCode_FullDetails"".
        /// </summary>
        public static string Description_Of_MSBuildExtensionPack_BuildEventCode_FullDetails {
            get {
                return ResourceManager.GetString("Description_Of_MSBuildExtensionPack_BuildEventCode_FullDetails", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "MSBuildExtensionPack_BuildEventCode_FullDetails"".
        /// </summary>
        public static string MSBuildExtensionPack_BuildEventCode_FullDetails {
            get {
                return ResourceManager.GetString("MSBuildExtensionPack_BuildEventCode_FullDetails", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "ToolTip Of MSBuildExtensionPack_BuildEventCode_FullDetails"".
        /// </summary>
        public static string ToolTip_Of_MSBuildExtensionPack_BuildEventCode_FullDetails {
            get {
                return ResourceManager.GetString("ToolTip_Of_MSBuildExtensionPack_BuildEventCode_FullDetails", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Description Of MSBuildExtensionPack_BuildEventCode_CommonSearchView"".
        /// </summary>
        public static string Description_Of_MSBuildExtensionPack_BuildEventCode_CommonSearchView {
            get {
                return ResourceManager.GetString("Description_Of_MSBuildExtensionPack_BuildEventCode_CommonSearchView", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "MSBuildExtensionPack_BuildEventCode_CommonSearchView"".
        /// </summary>
        public static string MSBuildExtensionPack_BuildEventCode_CommonSearchView {
            get {
                return ResourceManager.GetString("MSBuildExtensionPack_BuildEventCode_CommonSearchView", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "ToolTip Of MSBuildExtensionPack_BuildEventCode_CommonSearchView"".
        /// </summary>
        public static string ToolTip_Of_MSBuildExtensionPack_BuildEventCode_CommonSearchView {
            get {
                return ResourceManager.GetString("ToolTip_Of_MSBuildExtensionPack_BuildEventCode_CommonSearchView", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Description Of MSBuildExtensionPack_BuildEventCode_CommonResultView"".
        /// </summary>
        public static string Description_Of_MSBuildExtensionPack_BuildEventCode_CommonResultView {
            get {
                return ResourceManager.GetString("Description_Of_MSBuildExtensionPack_BuildEventCode_CommonResultView", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "MSBuildExtensionPack_BuildEventCode_CommonResultView"".
        /// </summary>
        public static string MSBuildExtensionPack_BuildEventCode_CommonResultView {
            get {
                return ResourceManager.GetString("MSBuildExtensionPack_BuildEventCode_CommonResultView", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "ToolTip Of MSBuildExtensionPack_BuildEventCode_CommonResultView"".
        /// </summary>
        public static string ToolTip_Of_MSBuildExtensionPack_BuildEventCode_CommonResultView {
            get {
                return ResourceManager.GetString("ToolTip_Of_MSBuildExtensionPack_BuildEventCode_CommonResultView", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Description Of MSBuildExtensionPack_BuildEventCode_TabbedCommon"".
        /// </summary>
        public static string Description_Of_MSBuildExtensionPack_BuildEventCode_TabbedCommon {
            get {
                return ResourceManager.GetString("Description_Of_MSBuildExtensionPack_BuildEventCode_TabbedCommon", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "MSBuildExtensionPack_BuildEventCode_TabbedCommon"".
        /// </summary>
        public static string MSBuildExtensionPack_BuildEventCode_TabbedCommon {
            get {
                return ResourceManager.GetString("MSBuildExtensionPack_BuildEventCode_TabbedCommon", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "ToolTip Of MSBuildExtensionPack_BuildEventCode_TabbedCommon"".
        /// </summary>
        public static string ToolTip_Of_MSBuildExtensionPack_BuildEventCode_TabbedCommon {
            get {
                return ResourceManager.GetString("ToolTip_Of_MSBuildExtensionPack_BuildEventCode_TabbedCommon", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Description Of MSBuildExtensionPack_BuildLog_Common"".
        /// </summary>
        public static string Description_Of_MSBuildExtensionPack_BuildLog_Common {
            get {
                return ResourceManager.GetString("Description_Of_MSBuildExtensionPack_BuildLog_Common", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "MSBuildExtensionPack_BuildLog_Common"".
        /// </summary>
        public static string MSBuildExtensionPack_BuildLog_Common {
            get {
                return ResourceManager.GetString("MSBuildExtensionPack_BuildLog_Common", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "ToolTip Of MSBuildExtensionPack_BuildLog_Common"".
        /// </summary>
        public static string ToolTip_Of_MSBuildExtensionPack_BuildLog_Common {
            get {
                return ResourceManager.GetString("ToolTip_Of_MSBuildExtensionPack_BuildLog_Common", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Description Of MSBuildExtensionPack_BuildLog_FullDetails"".
        /// </summary>
        public static string Description_Of_MSBuildExtensionPack_BuildLog_FullDetails {
            get {
                return ResourceManager.GetString("Description_Of_MSBuildExtensionPack_BuildLog_FullDetails", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "MSBuildExtensionPack_BuildLog_FullDetails"".
        /// </summary>
        public static string MSBuildExtensionPack_BuildLog_FullDetails {
            get {
                return ResourceManager.GetString("MSBuildExtensionPack_BuildLog_FullDetails", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "ToolTip Of MSBuildExtensionPack_BuildLog_FullDetails"".
        /// </summary>
        public static string ToolTip_Of_MSBuildExtensionPack_BuildLog_FullDetails {
            get {
                return ResourceManager.GetString("ToolTip_Of_MSBuildExtensionPack_BuildLog_FullDetails", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Description Of MSBuildExtensionPack_BuildLog_CommonSearchView"".
        /// </summary>
        public static string Description_Of_MSBuildExtensionPack_BuildLog_CommonSearchView {
            get {
                return ResourceManager.GetString("Description_Of_MSBuildExtensionPack_BuildLog_CommonSearchView", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "MSBuildExtensionPack_BuildLog_CommonSearchView"".
        /// </summary>
        public static string MSBuildExtensionPack_BuildLog_CommonSearchView {
            get {
                return ResourceManager.GetString("MSBuildExtensionPack_BuildLog_CommonSearchView", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "ToolTip Of MSBuildExtensionPack_BuildLog_CommonSearchView"".
        /// </summary>
        public static string ToolTip_Of_MSBuildExtensionPack_BuildLog_CommonSearchView {
            get {
                return ResourceManager.GetString("ToolTip_Of_MSBuildExtensionPack_BuildLog_CommonSearchView", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Description Of MSBuildExtensionPack_BuildLog_CommonResultView"".
        /// </summary>
        public static string Description_Of_MSBuildExtensionPack_BuildLog_CommonResultView {
            get {
                return ResourceManager.GetString("Description_Of_MSBuildExtensionPack_BuildLog_CommonResultView", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "MSBuildExtensionPack_BuildLog_CommonResultView"".
        /// </summary>
        public static string MSBuildExtensionPack_BuildLog_CommonResultView {
            get {
                return ResourceManager.GetString("MSBuildExtensionPack_BuildLog_CommonResultView", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "ToolTip Of MSBuildExtensionPack_BuildLog_CommonResultView"".
        /// </summary>
        public static string ToolTip_Of_MSBuildExtensionPack_BuildLog_CommonResultView {
            get {
                return ResourceManager.GetString("ToolTip_Of_MSBuildExtensionPack_BuildLog_CommonResultView", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Description Of MSBuildExtensionPack_BuildLog_TabbedCommon"".
        /// </summary>
        public static string Description_Of_MSBuildExtensionPack_BuildLog_TabbedCommon {
            get {
                return ResourceManager.GetString("Description_Of_MSBuildExtensionPack_BuildLog_TabbedCommon", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "MSBuildExtensionPack_BuildLog_TabbedCommon"".
        /// </summary>
        public static string MSBuildExtensionPack_BuildLog_TabbedCommon {
            get {
                return ResourceManager.GetString("MSBuildExtensionPack_BuildLog_TabbedCommon", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "ToolTip Of MSBuildExtensionPack_BuildLog_TabbedCommon"".
        /// </summary>
        public static string ToolTip_Of_MSBuildExtensionPack_BuildLog_TabbedCommon {
            get {
                return ResourceManager.GetString("ToolTip_Of_MSBuildExtensionPack_BuildLog_TabbedCommon", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Description Of MSBuildExtensionPack_Organization_Common"".
        /// </summary>
        public static string Description_Of_MSBuildExtensionPack_Organization_Common {
            get {
                return ResourceManager.GetString("Description_Of_MSBuildExtensionPack_Organization_Common", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "MSBuildExtensionPack_Organization_Common"".
        /// </summary>
        public static string MSBuildExtensionPack_Organization_Common {
            get {
                return ResourceManager.GetString("MSBuildExtensionPack_Organization_Common", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "ToolTip Of MSBuildExtensionPack_Organization_Common"".
        /// </summary>
        public static string ToolTip_Of_MSBuildExtensionPack_Organization_Common {
            get {
                return ResourceManager.GetString("ToolTip_Of_MSBuildExtensionPack_Organization_Common", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Description Of MSBuildExtensionPack_Organization_FullDetails"".
        /// </summary>
        public static string Description_Of_MSBuildExtensionPack_Organization_FullDetails {
            get {
                return ResourceManager.GetString("Description_Of_MSBuildExtensionPack_Organization_FullDetails", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "MSBuildExtensionPack_Organization_FullDetails"".
        /// </summary>
        public static string MSBuildExtensionPack_Organization_FullDetails {
            get {
                return ResourceManager.GetString("MSBuildExtensionPack_Organization_FullDetails", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "ToolTip Of MSBuildExtensionPack_Organization_FullDetails"".
        /// </summary>
        public static string ToolTip_Of_MSBuildExtensionPack_Organization_FullDetails {
            get {
                return ResourceManager.GetString("ToolTip_Of_MSBuildExtensionPack_Organization_FullDetails", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Description Of MSBuildExtensionPack_Organization_CommonSearchView"".
        /// </summary>
        public static string Description_Of_MSBuildExtensionPack_Organization_CommonSearchView {
            get {
                return ResourceManager.GetString("Description_Of_MSBuildExtensionPack_Organization_CommonSearchView", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "MSBuildExtensionPack_Organization_CommonSearchView"".
        /// </summary>
        public static string MSBuildExtensionPack_Organization_CommonSearchView {
            get {
                return ResourceManager.GetString("MSBuildExtensionPack_Organization_CommonSearchView", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "ToolTip Of MSBuildExtensionPack_Organization_CommonSearchView"".
        /// </summary>
        public static string ToolTip_Of_MSBuildExtensionPack_Organization_CommonSearchView {
            get {
                return ResourceManager.GetString("ToolTip_Of_MSBuildExtensionPack_Organization_CommonSearchView", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Description Of MSBuildExtensionPack_Organization_CommonResultView"".
        /// </summary>
        public static string Description_Of_MSBuildExtensionPack_Organization_CommonResultView {
            get {
                return ResourceManager.GetString("Description_Of_MSBuildExtensionPack_Organization_CommonResultView", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "MSBuildExtensionPack_Organization_CommonResultView"".
        /// </summary>
        public static string MSBuildExtensionPack_Organization_CommonResultView {
            get {
                return ResourceManager.GetString("MSBuildExtensionPack_Organization_CommonResultView", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "ToolTip Of MSBuildExtensionPack_Organization_CommonResultView"".
        /// </summary>
        public static string ToolTip_Of_MSBuildExtensionPack_Organization_CommonResultView {
            get {
                return ResourceManager.GetString("ToolTip_Of_MSBuildExtensionPack_Organization_CommonResultView", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Description Of MSBuildExtensionPack_Organization_TabbedCommon"".
        /// </summary>
        public static string Description_Of_MSBuildExtensionPack_Organization_TabbedCommon {
            get {
                return ResourceManager.GetString("Description_Of_MSBuildExtensionPack_Organization_TabbedCommon", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "MSBuildExtensionPack_Organization_TabbedCommon"".
        /// </summary>
        public static string MSBuildExtensionPack_Organization_TabbedCommon {
            get {
                return ResourceManager.GetString("MSBuildExtensionPack_Organization_TabbedCommon", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "ToolTip Of MSBuildExtensionPack_Organization_TabbedCommon"".
        /// </summary>
        public static string ToolTip_Of_MSBuildExtensionPack_Organization_TabbedCommon {
            get {
                return ResourceManager.GetString("ToolTip_Of_MSBuildExtensionPack_Organization_TabbedCommon", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Description Of MSBuildExtensionPack_Solution_Common"".
        /// </summary>
        public static string Description_Of_MSBuildExtensionPack_Solution_Common {
            get {
                return ResourceManager.GetString("Description_Of_MSBuildExtensionPack_Solution_Common", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "MSBuildExtensionPack_Solution_Common"".
        /// </summary>
        public static string MSBuildExtensionPack_Solution_Common {
            get {
                return ResourceManager.GetString("MSBuildExtensionPack_Solution_Common", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "ToolTip Of MSBuildExtensionPack_Solution_Common"".
        /// </summary>
        public static string ToolTip_Of_MSBuildExtensionPack_Solution_Common {
            get {
                return ResourceManager.GetString("ToolTip_Of_MSBuildExtensionPack_Solution_Common", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Description Of MSBuildExtensionPack_Solution_FullDetails"".
        /// </summary>
        public static string Description_Of_MSBuildExtensionPack_Solution_FullDetails {
            get {
                return ResourceManager.GetString("Description_Of_MSBuildExtensionPack_Solution_FullDetails", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "MSBuildExtensionPack_Solution_FullDetails"".
        /// </summary>
        public static string MSBuildExtensionPack_Solution_FullDetails {
            get {
                return ResourceManager.GetString("MSBuildExtensionPack_Solution_FullDetails", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "ToolTip Of MSBuildExtensionPack_Solution_FullDetails"".
        /// </summary>
        public static string ToolTip_Of_MSBuildExtensionPack_Solution_FullDetails {
            get {
                return ResourceManager.GetString("ToolTip_Of_MSBuildExtensionPack_Solution_FullDetails", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Description Of MSBuildExtensionPack_Solution_CommonSearchView"".
        /// </summary>
        public static string Description_Of_MSBuildExtensionPack_Solution_CommonSearchView {
            get {
                return ResourceManager.GetString("Description_Of_MSBuildExtensionPack_Solution_CommonSearchView", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "MSBuildExtensionPack_Solution_CommonSearchView"".
        /// </summary>
        public static string MSBuildExtensionPack_Solution_CommonSearchView {
            get {
                return ResourceManager.GetString("MSBuildExtensionPack_Solution_CommonSearchView", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "ToolTip Of MSBuildExtensionPack_Solution_CommonSearchView"".
        /// </summary>
        public static string ToolTip_Of_MSBuildExtensionPack_Solution_CommonSearchView {
            get {
                return ResourceManager.GetString("ToolTip_Of_MSBuildExtensionPack_Solution_CommonSearchView", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Description Of MSBuildExtensionPack_Solution_CommonResultView"".
        /// </summary>
        public static string Description_Of_MSBuildExtensionPack_Solution_CommonResultView {
            get {
                return ResourceManager.GetString("Description_Of_MSBuildExtensionPack_Solution_CommonResultView", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "MSBuildExtensionPack_Solution_CommonResultView"".
        /// </summary>
        public static string MSBuildExtensionPack_Solution_CommonResultView {
            get {
                return ResourceManager.GetString("MSBuildExtensionPack_Solution_CommonResultView", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "ToolTip Of MSBuildExtensionPack_Solution_CommonResultView"".
        /// </summary>
        public static string ToolTip_Of_MSBuildExtensionPack_Solution_CommonResultView {
            get {
                return ResourceManager.GetString("ToolTip_Of_MSBuildExtensionPack_Solution_CommonResultView", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Description Of MSBuildExtensionPack_Solution_TabbedCommon"".
        /// </summary>
        public static string Description_Of_MSBuildExtensionPack_Solution_TabbedCommon {
            get {
                return ResourceManager.GetString("Description_Of_MSBuildExtensionPack_Solution_TabbedCommon", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "MSBuildExtensionPack_Solution_TabbedCommon"".
        /// </summary>
        public static string MSBuildExtensionPack_Solution_TabbedCommon {
            get {
                return ResourceManager.GetString("MSBuildExtensionPack_Solution_TabbedCommon", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "ToolTip Of MSBuildExtensionPack_Solution_TabbedCommon"".
        /// </summary>
        public static string ToolTip_Of_MSBuildExtensionPack_Solution_TabbedCommon {
            get {
                return ResourceManager.GetString("ToolTip_Of_MSBuildExtensionPack_Solution_TabbedCommon", resourceCulture);
            }
        }

    }
}

