<?xml version="1.0" encoding="utf-8"?><Database Name="AdventureWorks2014" Class="dboDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.;Initial Catalog=AdventureWorks2014;Integrated Security=True" SettingsObjectName="Test2.Properties.Settings" SettingsPropertyName="AdventureWorks2014ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.AWBuildVersion" Member="AWBuildVersions">
    <Type Name="AWBuildVersion">
      <Column Name="SystemInformationID" Type="System.Byte" DbType="TinyInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="[Database Version]" Member="Database_Version" Type="System.String" DbType="NVarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="VersionDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.ErrorLog" Member="ErrorLogs">
    <Type Name="ErrorLog">
      <Column Name="ErrorLogID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ErrorTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="UserName" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="ErrorNumber" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ErrorSeverity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ErrorState" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ErrorProcedure" Type="System.String" DbType="NVarChar(126)" CanBeNull="true" />
      <Column Name="ErrorLine" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ErrorMessage" Type="System.String" DbType="NVarChar(4000) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.DatabaseLog" Member="DatabaseLogs">
    <Type Name="DatabaseLog">
      <Column Name="DatabaseLogID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PostTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="DatabaseUser" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="Event" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="[Schema]" Member="Schema" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="Object" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="TSQL" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="XmlEvent" Type="System.Xml.Linq.XElement" DbType="Xml NOT NULL" CanBeNull="false" UpdateCheck="Never" />
    </Type>
  </Table>
</Database>