ALTER TABLE [dbo].[BuildEventCode] NOCHECK CONSTRAINT ALL
ALTER TABLE [dbo].[Organization] NOCHECK CONSTRAINT ALL
ALTER TABLE [dbo].[Solution] NOCHECK CONSTRAINT ALL
ALTER TABLE [dbo].[Build] NOCHECK CONSTRAINT ALL
ALTER TABLE [dbo].[BuildLog] NOCHECK CONSTRAINT ALL


