//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSBuildExtensionPack.SQLiteEFContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class BuildLog
    {
        public long Id { get; set; }
        public long BuildId { get; set; }
        public long BuildEventCodeId { get; set; }
        public string Message { get; set; }
        public System.DateTime EventTime { get; set; }
    
        public virtual Build Build { get; set; }
        public virtual BuildEventCode BuildEventCode { get; set; }
    }
}
