//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSBuildExtensionPack.SQLiteEFContext
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MSBuildExtensionPackEntities : DbContext
    {
        public MSBuildExtensionPackEntities()
            : base("name=MSBuildExtensionPackEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Build> Builds { get; set; }
        public virtual DbSet<BuildEventCode> BuildEventCodes { get; set; }
        public virtual DbSet<BuildLog> BuildLogs { get; set; }
        public virtual DbSet<Organization> Organizations { get; set; }
        public virtual DbSet<Solution> Solutions { get; set; }
    }
}
