//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSBuildExtensionPack.SQLiteEFContext
{
    using System;
    using System.Collections.Generic;
    
    public partial class Organization
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Organization()
        {
            this.Organization1 = new HashSet<Organization>();
            this.Solutions = new HashSet<Solution>();
        }
    
        public long Id { get; set; }
        public long ParentId { get; set; }
        public string Name { get; set; }
        public bool IsSystemBuiltIn { get; set; }
        public System.Guid UniqueIdentifier { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public string CharColumn { get; set; }
        public string VarcharColumn { get; set; }
        public string TextColumn { get; set; }
        public string NcharColumn { get; set; }
        public string NvarcharColumn { get; set; }
        public string NtextColumn { get; set; }
        public bool BitColumn { get; set; }
        public byte[] BinaryColumn { get; set; }
        public byte[] VarbinaryColumn { get; set; }
        public byte[] ImageColumn { get; set; }
        public short TinyintColumn { get; set; }
        public short SmallintColumn { get; set; }
        public long IntColumn { get; set; }
        public long BigintColumn { get; set; }
        public decimal DecimalColumn { get; set; }
        public decimal NumericColumn { get; set; }
        public decimal SmallmoneyColumn { get; set; }
        public decimal MoneyColumn { get; set; }
        public double FloatColumn { get; set; }
        public double RealColumn { get; set; }
        public System.DateTime DatetimeColumn { get; set; }
        public System.DateTime Datetime2Column { get; set; }
        public System.DateTime SmalldatetimeColumn { get; set; }
        public System.DateTime DateColumn { get; set; }
        public System.DateTime TimeColumn { get; set; }
        public System.Guid UniqueidentifierColumn { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Organization> Organization1 { get; set; }
        public virtual Organization Organization2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Solution> Solutions { get; set; }
    }
}
