//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace MSBuildExtensionPack.EntityFrameworkContext
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
	using System.Data.Entity.Core.Objects;

    public partial class MSBuildExtensionPackEntities : DbContext
    {
        public MSBuildExtensionPackEntities()
            : base("name=MSBuildExtensionPackEntities")
        {
        }
    
        //protected override void OnModelCreating(DbModelBuilder modelBuilder)
        //{
        //    throw new UnintentionalCodeFirstException();
        //}
    

        public DbSet<Build> Builds { get; set; }



        public DbSet<BuildEventCode> BuildEventCodes { get; set; }



        public DbSet<BuildLog> BuildLogs { get; set; }



        public DbSet<Organization> Organizations { get; set; }



        public DbSet<Solution> Solutions { get; set; }





		#region GetAscendantOfParentIdOfMSBuildExtensionPack_Organization && GetDescendantOfParentIdOfMSBuildExtensionPack_Organization 

        public virtual ObjectResult<RecursivePathResultOfParentIdOfMSBuildExtensionPack_Organization> GetAscendantOfParentIdOfMSBuildExtensionPack_Organization(
			System.Int64 Id
			)
        {
			var IdParameter = new ObjectParameter("Id", Id);
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RecursivePathResultOfParentIdOfMSBuildExtensionPack_Organization>(
                "GetAscendantOfParentIdOfMSBuildExtensionPack_Organization"
				,IdParameter
				);
        }

        public virtual ObjectResult<RecursivePathResultOfParentIdOfMSBuildExtensionPack_Organization> GetDescendantOfParentIdOfMSBuildExtensionPack_Organization(
			System.Int64 Id
			)
        {
			var IdParameter = new ObjectParameter("Id", Id);
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RecursivePathResultOfParentIdOfMSBuildExtensionPack_Organization>(
                "GetDescendantOfParentIdOfMSBuildExtensionPack_Organization"
				, IdParameter
				);
        }

		#endregion GetAscendantOfParentIdOfMSBuildExtensionPack_Organization && GetDescendantOfParentIdOfMSBuildExtensionPack_Organization 


    }
}

