//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSBuildExtensionPack.EntityFrameworkContext
{
    using System;
    using System.Collections.Generic;

    #region partial class Build

    public partial class Build
    {
        public Build ()
        {
            this.BuildLogs = new HashSet<BuildLog>();

        }

        public System.Int64 Id { get; set; }
        public System.Int32 SolutionId { get; set; }
        public System.String Name { get; set; }
        public System.String Description { get; set; }
        public System.DateTime BuildStartTime { get; set; }

        public Solution Solution { get; set; }
        public ICollection<BuildLog> BuildLogs { get; set; }

    }

    #endregion partial class Build

    #region partial class BuildEventCode

    public partial class BuildEventCode
    {
        public BuildEventCode ()
        {
            this.BuildLogs = new HashSet<BuildLog>();

        }

        public System.Int32 Id { get; set; }
        public System.String EventCode { get; set; }
        public System.String Description { get; set; }

        public ICollection<BuildLog> BuildLogs { get; set; }

    }

    #endregion partial class BuildEventCode

    #region partial class BuildLog

    public partial class BuildLog
    {
        public BuildLog ()
        {

        }

        public System.Int64 Id { get; set; }
        public System.Int64 BuildId { get; set; }
        public System.Int32 BuildEventCodeId { get; set; }
        public System.String Message { get; set; }
        public System.DateTime EventTime { get; set; }

        public Build Build { get; set; }
        public BuildEventCode BuildEventCode { get; set; }

    }

    #endregion partial class BuildLog

    #region partial class Organization

    public partial class Organization
    {
        public Organization ()
        {
            this.Organization_ParentIds = new HashSet<Organization>();
            this.Solutions = new HashSet<Solution>();

        }

        public System.Int64 Id { get; set; }
        public System.Int64 ParentId { get; set; }
        public System.String Name { get; set; }
        public System.Boolean IsSystemBuiltIn { get; set; }
        public System.Guid UniqueIdentifier { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public System.String CharColumn { get; set; }
        public System.String VarcharColumn { get; set; }
        public System.String TextColumn { get; set; }
        public System.String NcharColumn { get; set; }
        public System.String NvarcharColumn { get; set; }
        public System.String NtextColumn { get; set; }
        public System.Boolean BitColumn { get; set; }
        public System.Byte[] BinaryColumn { get; set; }
        public System.Byte[] VarbinaryColumn { get; set; }
        public System.Byte[] ImageColumn { get; set; }
        public System.Byte TinyintColumn { get; set; }
        public System.Int16 SmallintColumn { get; set; }
        public System.Int32 IntColumn { get; set; }
        public System.Int64 BigintColumn { get; set; }
        public System.Decimal DecimalColumn { get; set; }
        public System.Decimal NumericColumn { get; set; }
        public System.Decimal SmallmoneyColumn { get; set; }
        public System.Decimal MoneyColumn { get; set; }
        public System.Single FloatColumn { get; set; }
        public System.Single RealColumn { get; set; }
        public System.DateTime DatetimeColumn { get; set; }
        public System.DateTime Datetime2Column { get; set; }
        public System.DateTime SmalldatetimeColumn { get; set; }
        public System.DateTime DateColumn { get; set; }
        public System.TimeSpan TimeColumn { get; set; }
        public System.Guid UniqueidentifierColumn { get; set; }

        public Organization Parent { get; set; }
        public ICollection<Organization> Organization_ParentIds { get; set; }
        public ICollection<Solution> Solutions { get; set; }

    }

    #endregion partial class Organization

    #region partial class Solution

    public partial class Solution
    {
        public Solution ()
        {
            this.Builds = new HashSet<Build>();

        }

        public System.Int32 Id { get; set; }
        public System.String ExternalParentId { get; set; }
        public System.String Name { get; set; }
        public System.String Description { get; set; }
        public System.Nullable<System.Int64> OrganizationId { get; set; }

        public Organization Organization { get; set; }
        public ICollection<Build> Builds { get; set; }

    }

    #endregion partial class Solution

    #region class RecursivePathResultOfParentIdOfMSBuildExtensionPack_Organization

    public partial class RecursivePathResultOfParentIdOfMSBuildExtensionPack_Organization
    {
        public System.Int64 Id { get; set; }
        public System.Int64 ParentId { get; set; }
        public System.String Name { get; set; }
        public System.Boolean IsSystemBuiltIn { get; set; }
        public System.Guid UniqueIdentifier { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public System.String CharColumn { get; set; }
        public System.String VarcharColumn { get; set; }
        public System.String TextColumn { get; set; }
        public System.String NcharColumn { get; set; }
        public System.String NvarcharColumn { get; set; }
        public System.String NtextColumn { get; set; }
        public System.Boolean BitColumn { get; set; }
        public System.Byte[] BinaryColumn { get; set; }
        public System.Byte[] VarbinaryColumn { get; set; }
        public System.Byte[] ImageColumn { get; set; }
        public System.Byte TinyintColumn { get; set; }
        public System.Int16 SmallintColumn { get; set; }
        public System.Int32 IntColumn { get; set; }
        public System.Int64 BigintColumn { get; set; }
        public System.Decimal DecimalColumn { get; set; }
        public System.Decimal NumericColumn { get; set; }
        public System.Decimal SmallmoneyColumn { get; set; }
        public System.Decimal MoneyColumn { get; set; }
        public System.Single FloatColumn { get; set; }
        public System.Single RealColumn { get; set; }
        public System.DateTime DatetimeColumn { get; set; }
        public System.DateTime Datetime2Column { get; set; }
        public System.DateTime SmalldatetimeColumn { get; set; }
        public System.DateTime DateColumn { get; set; }
        public System.TimeSpan TimeColumn { get; set; }
        public System.Guid UniqueidentifierColumn { get; set; }

        public string RecursivePath__ { get; set; }
    }

    #endregion class RecursivePathResultOfParentIdOfMSBuildExtensionPack_Organization

}

