//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MSBuildExtensionPack.Resources {
	using Windows.ApplicationModel.Resources;    
    
    public class UIStringResourcePerApp {
        
        private static ResourceLoader resourceLoader = new ResourceLoader("MSBuildExtensionPack.Resources/UIStringResourcePerApp");
        
        public UIStringResourcePerApp() {
        }


        /// <summary>
        ///   Looks up a localized string similar to "MSBuildExtensionPack"".
        /// </summary>
        public static string Application_Title {
            get {
                return resourceLoader.GetString("Application_Title");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Description Of Common of MSBuildExtensionPack.Build"".
        /// </summary>
        public static string Description_Of_Common_of_MSBuildExtensionPack_Build {
            get {
                return resourceLoader.GetString("Description_Of_Common_of_MSBuildExtensionPack_Build");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Common of MSBuildExtensionPack.Build"".
        /// </summary>
        public static string Common_of_MSBuildExtensionPack_Build {
            get {
                return resourceLoader.GetString("Common_of_MSBuildExtensionPack_Build");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "ToolTip Of Common of MSBuildExtensionPack.Build"".
        /// </summary>
        public static string ToolTip_Of_Common_of_MSBuildExtensionPack_Build {
            get {
                return resourceLoader.GetString("ToolTip_Of_Common_of_MSBuildExtensionPack_Build");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Description Of EntityRelated of MSBuildExtensionPack.Build"".
        /// </summary>
        public static string Description_Of_EntityRelated_of_MSBuildExtensionPack_Build {
            get {
                return resourceLoader.GetString("Description_Of_EntityRelated_of_MSBuildExtensionPack_Build");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "EntityRelated of MSBuildExtensionPack.Build"".
        /// </summary>
        public static string EntityRelated_of_MSBuildExtensionPack_Build {
            get {
                return resourceLoader.GetString("EntityRelated_of_MSBuildExtensionPack_Build");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "ToolTip Of EntityRelated of MSBuildExtensionPack.Build"".
        /// </summary>
        public static string ToolTip_Of_EntityRelated_of_MSBuildExtensionPack_Build {
            get {
                return resourceLoader.GetString("ToolTip_Of_EntityRelated_of_MSBuildExtensionPack_Build");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Description Of UpdateNameOnly of MSBuildExtensionPack.Build"".
        /// </summary>
        public static string Description_Of_UpdateNameOnly_of_MSBuildExtensionPack_Build {
            get {
                return resourceLoader.GetString("Description_Of_UpdateNameOnly_of_MSBuildExtensionPack_Build");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "UpdateNameOnly of MSBuildExtensionPack.Build"".
        /// </summary>
        public static string UpdateNameOnly_of_MSBuildExtensionPack_Build {
            get {
                return resourceLoader.GetString("UpdateNameOnly_of_MSBuildExtensionPack_Build");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "ToolTip Of UpdateNameOnly of MSBuildExtensionPack.Build"".
        /// </summary>
        public static string ToolTip_Of_UpdateNameOnly_of_MSBuildExtensionPack_Build {
            get {
                return resourceLoader.GetString("ToolTip_Of_UpdateNameOnly_of_MSBuildExtensionPack_Build");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Description Of Common of MSBuildExtensionPack.BuildEventCode"".
        /// </summary>
        public static string Description_Of_Common_of_MSBuildExtensionPack_BuildEventCode {
            get {
                return resourceLoader.GetString("Description_Of_Common_of_MSBuildExtensionPack_BuildEventCode");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Common of MSBuildExtensionPack.BuildEventCode"".
        /// </summary>
        public static string Common_of_MSBuildExtensionPack_BuildEventCode {
            get {
                return resourceLoader.GetString("Common_of_MSBuildExtensionPack_BuildEventCode");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "ToolTip Of Common of MSBuildExtensionPack.BuildEventCode"".
        /// </summary>
        public static string ToolTip_Of_Common_of_MSBuildExtensionPack_BuildEventCode {
            get {
                return resourceLoader.GetString("ToolTip_Of_Common_of_MSBuildExtensionPack_BuildEventCode");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Description Of EntityRelated of MSBuildExtensionPack.BuildEventCode"".
        /// </summary>
        public static string Description_Of_EntityRelated_of_MSBuildExtensionPack_BuildEventCode {
            get {
                return resourceLoader.GetString("Description_Of_EntityRelated_of_MSBuildExtensionPack_BuildEventCode");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "EntityRelated of MSBuildExtensionPack.BuildEventCode"".
        /// </summary>
        public static string EntityRelated_of_MSBuildExtensionPack_BuildEventCode {
            get {
                return resourceLoader.GetString("EntityRelated_of_MSBuildExtensionPack_BuildEventCode");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "ToolTip Of EntityRelated of MSBuildExtensionPack.BuildEventCode"".
        /// </summary>
        public static string ToolTip_Of_EntityRelated_of_MSBuildExtensionPack_BuildEventCode {
            get {
                return resourceLoader.GetString("ToolTip_Of_EntityRelated_of_MSBuildExtensionPack_BuildEventCode");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Description Of Common of MSBuildExtensionPack.BuildLog"".
        /// </summary>
        public static string Description_Of_Common_of_MSBuildExtensionPack_BuildLog {
            get {
                return resourceLoader.GetString("Description_Of_Common_of_MSBuildExtensionPack_BuildLog");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Common of MSBuildExtensionPack.BuildLog"".
        /// </summary>
        public static string Common_of_MSBuildExtensionPack_BuildLog {
            get {
                return resourceLoader.GetString("Common_of_MSBuildExtensionPack_BuildLog");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "ToolTip Of Common of MSBuildExtensionPack.BuildLog"".
        /// </summary>
        public static string ToolTip_Of_Common_of_MSBuildExtensionPack_BuildLog {
            get {
                return resourceLoader.GetString("ToolTip_Of_Common_of_MSBuildExtensionPack_BuildLog");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Description Of EntityRelated of MSBuildExtensionPack.BuildLog"".
        /// </summary>
        public static string Description_Of_EntityRelated_of_MSBuildExtensionPack_BuildLog {
            get {
                return resourceLoader.GetString("Description_Of_EntityRelated_of_MSBuildExtensionPack_BuildLog");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "EntityRelated of MSBuildExtensionPack.BuildLog"".
        /// </summary>
        public static string EntityRelated_of_MSBuildExtensionPack_BuildLog {
            get {
                return resourceLoader.GetString("EntityRelated_of_MSBuildExtensionPack_BuildLog");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "ToolTip Of EntityRelated of MSBuildExtensionPack.BuildLog"".
        /// </summary>
        public static string ToolTip_Of_EntityRelated_of_MSBuildExtensionPack_BuildLog {
            get {
                return resourceLoader.GetString("ToolTip_Of_EntityRelated_of_MSBuildExtensionPack_BuildLog");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Description Of Common of MSBuildExtensionPack.Solution"".
        /// </summary>
        public static string Description_Of_Common_of_MSBuildExtensionPack_Solution {
            get {
                return resourceLoader.GetString("Description_Of_Common_of_MSBuildExtensionPack_Solution");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Common of MSBuildExtensionPack.Solution"".
        /// </summary>
        public static string Common_of_MSBuildExtensionPack_Solution {
            get {
                return resourceLoader.GetString("Common_of_MSBuildExtensionPack_Solution");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "ToolTip Of Common of MSBuildExtensionPack.Solution"".
        /// </summary>
        public static string ToolTip_Of_Common_of_MSBuildExtensionPack_Solution {
            get {
                return resourceLoader.GetString("ToolTip_Of_Common_of_MSBuildExtensionPack_Solution");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "Description Of EntityRelated of MSBuildExtensionPack.Solution"".
        /// </summary>
        public static string Description_Of_EntityRelated_of_MSBuildExtensionPack_Solution {
            get {
                return resourceLoader.GetString("Description_Of_EntityRelated_of_MSBuildExtensionPack_Solution");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "EntityRelated of MSBuildExtensionPack.Solution"".
        /// </summary>
        public static string EntityRelated_of_MSBuildExtensionPack_Solution {
            get {
                return resourceLoader.GetString("EntityRelated_of_MSBuildExtensionPack_Solution");
            }
        }


        /// <summary>
        ///   Looks up a localized string similar to "ToolTip Of EntityRelated of MSBuildExtensionPack.Solution"".
        /// </summary>
        public static string ToolTip_Of_EntityRelated_of_MSBuildExtensionPack_Solution {
            get {
                return resourceLoader.GetString("ToolTip_Of_EntityRelated_of_MSBuildExtensionPack_Solution");
            }
        }


    }
}